### ISSUE TITLE
Question about making index by sequencing_summary.txt

### ISSUE THREAD

**Issue by Liamoki** [MBoemo/DNAscent#1]
Hi, 
Thanks for this BrdU tool, it really helps.
I am recently doing a small project for my bachelor graduation thesis where I need to count the BrdU incorporation and its density. 
Basecalled by albacore, .fastq files, as well as a sequencing_summary.txt, are provided. Then I write these .fastq files into a single .fq.gz file and delete these old ones. 
Can I use the BAM provided by the .fq.gz file together with the index made by sequencing_summary.txt for `DNAscent detect`?
thanks.

**Comment by MBoemo** [comment]
Hi, very sorry for the late reply!  Just to make sure I understand, you have fast5 files that were basecalled by Albacore, the fastq basecalls from Albacore, and a sequencing summary file?  If so, run DNAscent index on the top level directory with the fast5 files (and also pass it the sequencing summary file so it runs faster), align your basecalls to the appropriate genome to get a bam file, and then you should be able to run DNAscent detect.  The resulting file will give you a log likelihood of BrdU vs thymidine for each position - we generally consider a log likelihood > 2.5 to be a positive BrdU call.  From there, you should be able to write a quick script that counts the positive calls and calculates a density (or do this with DNAscent regions if you want).  Don't hesitate to get in touch if you run into any issues.
