### ISSUE TITLE
error catch

### ISSUE THREAD

**Issue by john-alexander** [MBoemo/DNAscent#14]
Hi Michael,

Adding these for reference - these errors were thrown owing to lack of reads in detect file. 

[run.DNAScent.detect_barcode06.1129555.err.txt](https://github.com/MBoemo/DNAscent/files/6295884/run.DNAScent.detect_barcode06.1129555.err.txt)
[run.DNAScent.detect_barcode09.1129556.err.txt](https://github.com/MBoemo/DNAscent/files/6295887/run.DNAScent.detect_barcode09.1129556.err.txt)

Kind regards,

John

**Comment by MBoemo** [comment]
Thanks John, I'll roll this into the next release.
