### ISSUE TITLE
MissingFast5 Error - File structure issue?

### ISSUE THREAD

**Issue by GeoMicroSoares** [MBoemo/DNAscent#20]
Hi there @MBoemo ,

I have followed all instructions to clone and compile the repository and `DNAscent` seems to be correctly installed. However, trying to run `DNAscent index`, I run into the following error:

```
DNAscent index -f all_fast5/ -s sequencing_summary_FAQ55717_455e1de5.txt -o ~/test_DNAscent/index.dnascent
terminate called after throwing an instance of 'MissingFast5'
  what():  In specified directory, couldn't find fast5 file: FAQ55717_fail_455e1de5_0.fastq.gz
Aborted (core dumped)
```

Briefly, I've copied all `.fast5` files (failed and passed) to an `all_fast5` folder, then run `DNAscent` as above. I have permissions to all folders and this error has occurred with and without sudo. I don't think this should impact `DNAscent` very much, but this run was on a R10.4 ONT flowcell.
The file in question (`FAQ55717_fail_455e1de5_0.fastq.gz`) by the way, exists and is in `fastq_fail` as per ONT standard run parameters - but I thought this step of the workflow wasn't supposed to look at `.fastq` but instead `.fast5`...

I'm running the latest version of DNAscent as per below:

```
$ git describe --tags
2.0.2
$ git rev-parse HEAD
ab844162b9cb707d68714d3c58f5dc8a41b29ae0
```
Please let me know if you need any other information - I'm really lost as to why this is happening at this point... And many thanks in advance!

**Comment by MBoemo** [comment]
Did you do the sequencing on a GridION?  If so, my guess is it's a repeat of https://github.com/MBoemo/DNAscent/issues/19

**Comment by GeoMicroSoares** [comment]
Done on a minION - just running a R10.4 flowcell. Thanks for the quick reply!

**Comment by MBoemo** [comment]
R10.4 is probably the issue then.  At the moment, DNAscent only supports R9.4.1 flowcells.

**Comment by GeoMicroSoares** [comment]
I wonder why though - I don't think the structure of the `.fast5` files changed and the `sequencing_summary.txt` file is the same format too. If anything, R10.4 would give `DNAscent` better resolution... 
If you're willing and can think of where the error comes from I can try some fixes that can lead to a new version of `DNAscent`?

**Comment by can1002** [comment]
Hi André, DNAscent needs a trained model, just like guppy. The model is pore-specific and based on training data that we collected on R9.4. To work with R10.4 would require a new model, etc.

**Comment by GeoMicroSoares** [comment]
Hi @can1002 , thanks for the explanation - had no idea! Well, I can see how that would mean a considerable amount of work, but if I can contribute to building/updating that model please let me know. I don't see e.g. a toolkit to do that on the user side, so I guess it would be solely up to the developers, but the interest in using this tool with an R10.4 model remains. R10+ data generation in general should increase quite a lot as this year goes by...
