### ISSUE TITLE
Calling other base analogs?

### ISSUE THREAD

**Issue by altemose** [MBoemo/DNAscent#21]
Hello and thanks for the excellent work on this. Can DNAscent v2 detect other base analogs like EdU with any accuracy out of the box? (Not multiple analogs simultaneously, just EdU instead of BrdU). If not, is it possible for the user to retrain the residual neural net on control samples?

**Comment by MBoemo** [comment]
Replied in DM, closing.

**Comment by najohink** [comment]
I too was wondering how DNAscent would perform out of the box on other dU analogues. Any insight or suggestions would be appreciated. Thanks!

**Comment by MBoemo** [comment]
At the moment, only BrdU and EdU are supported, but we're working on a few other possibilities.
