### ISSUE TITLE
Issus with DNAdetect

### ISSUE THREAD

**Issue by MaximeLcnrs** [MBoemo/DNAscent#23]
Hello, 

I'm using your software to detect BrdU in freshly sequenced Nanopore reads. I'm running DNAindex without any problem but when I'm trying to use DNAscent detect, I have the following report: 

Loading DNAscent index... ok.
Importing reference... ok.
Opening bam file... ok.
Scanning bam file...ok.
[>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed: [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  [>                                  ]   0%      0/3794   0hr 0min 0sec  failed:  HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140696010117632:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 550 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1872 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2902 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1357 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 298 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 402 in H5PL__find(): can't open directory
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
DNAscent: src/event_handling.cpp:635: void normaliseEvents(read&, bool): Assertion `et.n > 0' failed.
Abandon

I've try to re-basecalled the reads, re-do every previous steps but always have the same issues. 
Did you have any suggestions ? 

Sincerely,
Maxime

**Comment by MaximeLcnrs** [comment]
Hi, 
Thanks for your response. I've already have the plugin, see the path below: 

/homegalio2/maximel/Nanopore_analysis/DNAscent/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/libvbz_hdf_plugin.so

Should I put the plugin directly on the hdf5 directory from DNAscent ? Like put it directly in the path below ? 

/homegalio2/maximel/Nanopore_analysis/DNAscent/hdf5-1.8.14/hdf5/lib/

Sorry if the response is obvious, I'm quitte a newby with linux... 

Sincerely,
Maxime

**Comment by sathish-t** [comment]
Hi, I think the plugin can be in any directory. You would have to do the export command below before running DNAscent.

export HDF5_PLUGIN_PATH=/homegalio2/maximel/Nanopore_analysis/DNAscent/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/

**Comment by MaximeLcnrs** [comment]
My god, can't believe it was so simple! 
I re-run the DNAscent detect and I guess it's working. I'm at 1% of the analysis so I can't be happy too soon! 
I'll come back later to tell you if you saved my day! 

Thank you so much !

**Comment by MBoemo** [comment]
Thanks for resolving - repeat of https://github.com/MBoemo/DNAscent/issues/17 so closing.
