### ISSUE TITLE
Could not open file: index.dnascent

### ISSUE THREAD

**Issue by rmayang28** [MBoemo/DNAscent#24]
Hi, 

I have downloaded DNAscent and when running DNAscent command, I could see all the proper executables. But when I try to run `./DNAscent index -f /data/a/PEAP/pION/MinION/20220511_exp1_ku80/20220511_exp1/no_sample/20220511_1300_MN38257_FAR60553_a490da1d/fast5_pass/`
  I would get an error message:
```
terminate called after throwing an instance of 'IOerror'
  what():  Could not open file: index.dnascent
Aborted
```
Please let me know what I should do to try and fix this. 

Thank you
Mai

**Comment by MBoemo** [comment]
It looks like you don't have write permissions to the folder you're running DNAscent from, hence it can't write the index output file.  I'd try creating a folder you know you can write to, and then run DNAscent index from there.  Or, alternatively, you can specify the path of the output file you want with `-o`.  Closing for now, but reopen if that doesn't fix it.
