### ISSUE TITLE
I0 error-DNAscent detect

### ISSUE THREAD

**Issue by MaximeLcnrs** [MBoemo/DNAscent#25]
Hi, 

I have run software many times in the past but today I have an issue that I have never had before. 
DNAscent detect run for minutes when and then brutally stop and I have this message: 

[>                                  ]   HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140238876975616:
 #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1085 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 294 in H5F_super_read(): unable to load superblock
    major: Object cache
    minor: Unable to protect metadata
  #003: H5AC.c line 1320 in H5AC_protect(): H5C_protect() failed.
    major: Object cache
    minor: Unable to protect metadata
  #004: H5C.c line 3574 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #005: H5C.c line 7954 in H5C_load_entry(): unable to load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #006: H5Fsuper_cache.c line 476 in H5F_sblock_load(): truncated file: eof = 25100288, sblock->base_addr = 0, stored_eoa = 259457540
    major: File accessibilty
    minor: File has been truncated
terminate called after throwing an instance of 'IOerror'
  what():  Could not open file: /homegalio2/maximel/BrdU_analysis/Data_seq3/Fast5/FAT03526_pass_271b40b5_253.fast5
0%      624/916826  269hr14min27sec  failed:      26  
[>                                  ]   0%      624/916826  269hr14min27sec  failed:      26  
[>                                  ]   0%      624/916826  269hr14min27sec  failed:      26  
[>                                  ]   0%      624/916826  269hr14min27sec  failed:      26  
[>                                  ]   0%      625/916826  269hr11min58sec  failed:      26  
[>                                  ]   0%      626/916826  270hr47min26sec  failed:      26  
srun: error: node21: task 0: Aborted

It seems to be a accessibility problem but I have all access to the differents files. 
Have you be faced to this issue before ? 
How can i solve that ? 

It's the first time I use DNAscent since the update of Guppy, and I generate fast5 files with MinION on R9.4.1 flowcells. 

Best, 
Maxime

**Comment by MaximeLcnrs** [comment]
Hi, 
Thanks for the quick reply. 
I can confirm that the path is correct. 

It looks like the same issue than this one:  https://github.com/MBoemo/DNAscent/issues/16#issue-945523424 
but in my case, DNAscent work for some a bit. 

Best,

**Comment by MBoemo** [comment]
Based on the HDF5 warnings about file truncation, and the fact that it ran for a while before crashing, my suspicion would be that there's an issue with at least one of your fast5 files (possibly corrupted during an upload?). Can you try rerunning without `FAT03526_pass_271b40b5_253.fast5` to see if that resolves the issue?

**Comment by MaximeLcnrs** [comment]
Did I have to rerun the alignment without the fastq corresponding to FAT03526_pass_271b40b5_253.fast5 ? 
Or just rerun DNAscent detect without FAT03526_pass_271b40b5_253.fast5 ?

**Comment by MBoemo** [comment]
You'd have to re-run the alignment I'm afraid. I personally haven't encountered this particular issue before, but it seems consistent with a corrupted fast5 and has cropped up on occasion with nanopolish (e.g., https://github.com/jts/nanopolish/issues/132). @jts did you ever get to the bottom of this?

**Comment by MaximeLcnrs** [comment]
Thanks for your quick responses, it help us a lot! 

So, I re-run the analysis without the suspect file and it's working for now (Since 1 hour) 
I will try to run nanopolish later. 

Thanks for your precise and very quick answers. 
Best,
Maxime

**Comment by MBoemo** [comment]
Great - I'm going to assume it was a one-off corrupted file and close, but reopen if you have any further problems.
