### ISSUE TITLE
BrdU metrics for output of forkSense 

### ISSUE THREAD

**Issue by dariober** [MBoemo/DNAscent#27]
Hello - I'm wondering whether there could be any value in annotating each feature detected by forkSense with some metrics about BrdU. The reason would be to give some sense of the reliability of the feature. I'm thinking for example of something like "median P(BrdU)" and/or "% sites with P(BrdU) > cutoff" etc.

I'm happy to whip up a script for that but before I go too far I wanted to ask your opinion... Would it be any useful...? Thanks!

**Comment by MBoemo** [comment]
There's something similar to this in the forkSense header, which shows the estimated BrdU (and EdU) substitution in BrdU-positive (and EdU-positive) regions. For something like this, you could do a simple variation on what we put in the Python cookbook (https://dnascent.readthedocs.io/en/latest/cookbook.html):

```
import numpy as np
f = open('path/to/output.detect','r')

BrdU_probabilities = []
P_cutoff = 0.5
BrdUpositive_sites = 0
allSites = 0

for line in f:

     #ignore the header lines
     if line[0] == '#':
             continue

     #split the line into a list by whitespace
     splitLine = line.rstrip().split()

     if line[0] == '>':

             readID = splitLine[0][1:]
             chromosome = splitLine[1]
             refStart = int(splitLine[2])
             refEnd = int(splitLine[3])
             strand = splitLine[4]
     else:
             posOnRef = int(splitLine[0])
             probEdU = float(splitLine[1])
             probBrdU = float(splitLine[2])
             sixMerOnRef = splitLine[3]

             BrdU_probabilities.append(probBrdU)
             if probBrdU > P_cutoff:
                          BrdUpositive_sites += 1
             allSites += 1
f.close()
print('Median BrdU probability:',np.median(BrdU_probabilities))
print('% sites with P(BrdU) greater than cutoff:',float(BrdUpositive_sites)/allSites*100.)
```
If you have a lot of reads, maybe be careful that `BrdU_probabilities` doesn't become massive - just cap it after a certain number of reads to get an approximation.
