### ISSUE TITLE
DNAscent detect issue - failed reads

### ISSUE THREAD

**Issue by MiHern** [MBoemo/DNAscent#28]
Hello,

When running DNAscent detect we are getting 100% failed reads (up to 1% running, at least). What does failed mean? Is it a mapQ problem? An indexing issue? Something related to the nucleotide analog calling itself?

Regards,

Miguel.

**Comment by MBoemo** [comment]
Sorry for the late reply - the percentage failed reads on the progress bar indicates that the reads have failed signal alignment quality controls. Reads that don't meet the mapping length or quality that you specify are ignored completely, so they're not counted as failed. A typical failure rate is about 10-15%, so 100% failure rate is definitely indicative of some issue. Can I just confirm that you're using R9.4.1 flow cells, and if so, can you either post, DM, or Email me what you're trying to do and we'll get this resolved?

**Comment by MiHern** [comment]
No worries. We used a R10 flow cell. It is not compatible, right?

**Comment by MBoemo** [comment]
Yes that'll be the issue - only R9.4.1 flow cells are compatible right now. We're working on R10 support and this will come out in a future release.

**Comment by MiHern** [comment]
My bad, thanks for the info.

**Comment by SQYSunny** [comment]
Hello, I am wondering if R10 compatible version is available? I ran into the same issue. Thank you!

**Comment by MBoemo** [comment]
I can confirm there is an R10 version in development which we aim to make available soon.
