### ISSUE TITLE
DNAscent index, detect

### ISSUE THREAD

**Issue by john-alexander** [MBoemo/DNAscent#3]
Dear Michael A. Boemo,

Thank you for this tool. 

Pretty new to Nanopore sequencing; I seem to have run into a few issues whilst trying to use DNAscent starting on fastq files generated during the sequence run. 

Raw directory :

fast5_fail/
fast5_pass/
**fastq_fail/**
**fastq_pass/**
--barcode01
--barcode02
--barcode03
--barcode04
--barcode05
--barcode07
--barcode08
--barcode09
--barcode11
--barcode12
--unclassified

Initial pipeline was setup to run using the raw fast5 by 
1) running guppy_basecaller on fast5 folders (pass, skip, fail) 
2) DNAscent index using sequence_summary file generated in step1
3) aligning using minimap
4) samtools sort, index 
5) DNAscent detect 

Trouble with running on .fast5 files was that it was taking way too long at the base calling step - so proceeded to use the fastq files generated by the sequencer.

Attempting to starting from fastq files and sequence summary files :

 `DNAscent index -f /path/to/20191031_1733_MN20656_FAK47244_97c2b642/ -s path/to/20191031_1733_MN20656_FAK47244_97c2b642/11564brklt.local_20191031_173318_FAK47244_minion_sequencing_run_Dan9_sequencing_summary.txt` 

**terminate called after throwing an instance of 'MissingFast5'
  what():  In specified directory, couldn't find fast5 file: FAK47244_83da629f91a70a37ab31d56ab51465f70ee209a4_0.fastq
Aborted (core dumped)**

I ended up excluding 11564brklt.local_20191031_173318_FAK47244_minion_sequencing_run_Dan9_sequencing_summary.txt

`DNAscent index -f /path/to/rawdata/20191031_1733_MN20656_FAK47244_97c2b642/ `

This worked but seemed to contain only the **fast5_pass/** file path (not fastq) and contained only **barcode03 fast5** indices.

Testing using this index file on barcode03 fastq sample (btw, I run the following commands on each fastq file separately instead of combining them): 

```
minimap2 -ax map-ont path/to/GRCh38.d1.vd1.fa  path/to/fastq_pass/barcode03/FAK47244_83da629f91a70a37ab31d56ab51465f70ee209a4_0.fastq > ./sam/FAK47244_83da629f91a70a37ab31d56ab51465f70ee209a4_0.sam 

samtools sort -O BAM ./sam/FAK47244_83da629f91a70a37ab31d56ab51465f70ee209a4_0.sam  -o ./bam/FAK47244_83da629f91a70a37ab31d56ab51465f70ee209a4_0.bam

samtools index ./bam/FAK47244_83da629f91a70a37ab31d56ab51465f70ee209a4_0.bam

DNAscent detect -b ./bam/FAK47244_83da629f91a70a37ab31d56ab51465f70ee209a4_0.bam -r 
path/to/GRCh38.d1.vd1.fa -i path/to/index.dnascent -o ./DNAscent_detect/output_0.detect -t 10
``` 
Threw up the following error:

**Building analogue model... 159 analogue-containing 6mers.
Loading DNAscent index... ok.
Importing reference... ok.
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47474082395904: 0sec  f:     0  
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47474084497152:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47474092902144:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47474088699648:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47474076768000:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47474086598400:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47474097104640:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47474095003392:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47474038741504:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 47474090800896:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
terminate called after throwing an instance of 'IOerror'
  what():  Could not open file: 
Aborted (core dumped)**

Please do let me know if I've done something colossally wrong/how to resolve the above?

Kind regards,

John

**Comment by MBoemo** [comment]
Very sorry for the late reply.  Just want to double check - with the `-f` flag to DNAscent index, are you passing it the directory to the .fastq files (from Guppy) or the .fast5 files?  You'll want to pass it the directory to the fast5 files.  Sorry in advance if I misunderstood.

**Comment by john-alexander** [comment]
Dear Michael,

Thanks for getting back.


I am passing the directory containing both fast5, fastq folders.

> [jalexander01@login1(#####) 20191031_1733_MN20656_FAK47244_97c2b642]$ ls -rlth
drwxr-sr-x+ 15 xXXXX xxxxx 4.0K Nov  6 23:41 fast5_pass
drwxr-sr-x+ 13 xXXXX xxxxx 4.0K Nov  6 23:42 fast5_fail
drwxr-sr-x+ 15 xXXXX xxxxx 4.0K Nov 18 11:36 fastq_pass
-rw-r--r--+  1 xXXXX xxxxx 274M Nov 18 11:42 11564brklt.local_20191031_173318_FAK47244_minion_sequencing_run_Dan9_sequencing_summary.txt
drwxr-sr-x+ 13 xXXXX xxxxx 4.0K Nov 18 12:44 fastq_fail

I've just tried the following (pointing to fast5 or fastq):

 `[jalexander01@login1(xxxx) 20191031_1733_MN20656_FAK47244_97c2b642]$  DNAscent index -f path/to/20191031_1733_MN20656_FAK47244_97c2b642/fast5_pass -s /path/to/20191031_1733_MN20656_FAK47244_97c2b642/11564brklt.local_20191031_173318_FAK47244_minion_sequencing_run_Dan9_sequencing_summary.txt `

**terminate called after throwing an instance of 'MissingFast5'
  what():  In specified directory, couldn't find fast5 file: FAK47244_83da629f91a70a37ab31d56ab51465f70ee209a4_0.fastq
Aborted**
```
[jalexander01@login1(xxxx) 20191031_1733_MN20656_FAK47244_97c2b642]$ 

[jalexander01@login1(xxxx) 20191031_1733_MN20656_FAK47244_97c2b642]$  DNAscent index -f /path/to/20191031_1733_MN20656_FAK47244_97c2b642/fastq_pass -s /path/to/20191031_1733_MN20656_FAK47244_97c2b642/11564brklt.local_20191031_173318_FAK47244_minion_sequencing_run_Dan9_sequencing_summary.txt 
```
**terminate called after throwing an instance of 'MissingFast5'
  what():  In specified directory, couldn't find fast5 file: FAK47244_83da629f91a70a37ab31d56ab51465f70ee209a4_0.fastq
Aborted**

Using the sequence summary file dint work.
Without this just generated an DNAscent.index file with only **fast5_pass** inside it which I used to test DNAScent detect.

**Comment by MBoemo** [comment]
When you ran `DNAscent index -f path/to/20191031_1733_MN20656_FAK47244_97c2b642/fast5_pass -s /path/to/20191031_1733_MN20656_FAK47244_97c2b642/11564brklt.local_20191031_173318_FAK47244_minion_sequencing_run_Dan9_sequencing_summary.txt` you're replacing `/path/to/` with the actual full path to these files/directories on your file system right?  Not literally typing `/path/to/`?  So if you navigate to `20191031_1733_MN20656_FAK47244_97c2b642` and run `pwd`, the output of that should be what you pass to `-f`.

**Comment by john-alexander** [comment]
Yes correct, thats what I've done. Sorry, masked the output for data protection.

**Comment by MBoemo** [comment]
Okay that's what I thought, just wanted to double check.  Can you pull from master, run `git log -1` to make sure you're on commit 39fd07c, `make clean` and recompile?  There was a small input handling bug that I think was causing the issue.  Let me know if that fixes it.

**Comment by john-alexander** [comment]
Hi Michael,

Sorry for the delayed response.  I just tested with the latest version and it seems to throw the same error

```
[jalexander01@dav002(davros) DNAscent]$ git log -1
commit 39fd07cfdb71462f160185e075f5c5eb654bd964
Author: Michael Boemo <m.a.boemo@gmail.com>
Date:   Fri Jan 17 16:30:45 2020 +0000

    DNAscent index input handling
```

Tried all 3 commands
```
DNAscent index -f /scratch/DBC/xxx/20191031_1733_MN20656_FAK47244_97c2b642/ -s 	/scratch/DBC/xxx/20191031_1733_MN20656_FAK47244_97c2b642/11564brklt.local_20191031_173318_FAK47244_minion_sequencing_run_Dan9_sequencing_summary.txt 
DNAscent index -f /scratch/DBC/xxx/20191031_1733_MN20656_FAK47244_97c2b642/fast5_pass -s /scratch/DBC/xxx/20191031_1733_MN20656_FAK47244_97c2b642/11564brklt.local_20191031_173318_FAK47244_minion_sequencing_run_Dan9_sequencing_summary.txt 
DNAscent index -f /scratch/DBC/xxx/20191031_1733_MN20656_FAK47244_97c2b642/fastq_pass -s /scratch/DBC/xxx/20191031_1733_MN20656_FAK47244_97c2b642/11564brklt.local_20191031_173318_FAK47244_minion_sequencing_run_Dan9_sequencing_summary.txt 
```
**terminate called after throwing an instance of 'MissingFast5'
  what():  In specified directory, couldn't find fast5 file: FAK47244_83da629f91a70a37ab31d56ab51465f70ee209a4_0.fastq
Aborted (core dumped)**


On the other hand - ive managed to redo the basecalling with guppy using fast5 files- used the new sequence_summary.txt generated file to create a DNAscent.index file.

Maybe there is a difference in sequence_summary file owing to different guppy versions.

**Comment by MBoemo** [comment]
Unfortunately I haven't managed to reproduce this error yet.  Did you rename the sequencing summary file out of Guppy?  It's usually just called `sequencing_summary.txt` and is located in the folder passed to Guppy with the `-s` flag.  If possible, can you send me the sequencing summary file so I can take a look?  Also, can you let me know the version of Guppy you're using and the arguments you used to do the basecalling?
