### ISSUE TITLE
Recursively search for fast5 file

### ISSUE THREAD

**Issue by DidiCi** [MBoemo/DNAscent#30]
Good morning,
I wanted to know if there is a way to recursively search for fast5 files when creating the index. Also, just for info, the index function seems not to work when the first column of the sequencing_summary reports the fastq and not the fast5.
Thank you in advance
Diletta

**Comment by MBoemo** [comment]
DNAscent index should search recursively for any file with the fast5 extension already, so you can just point it to the top-level directory with your fast5 files in it. The problem with the columns stems from devices (like the GridION) with built-in basecalling producing a sequencing summary file with a slightly different format compared to the one produced by the downloadable version of Guppy. You should be able to fix that by adding the `--GridION` flag to the DNAscent index command, which will shift the columns appropriately. Closing for now, but reopen if that doesn't fix it.
