### ISSUE TITLE
DNAsent index error "Could not open file"

### ISSUE THREAD

**Issue by altemose** [MBoemo/DNAscent#32]
Hi Mike, 

I've been struggling to run DNAscent index or DNAscent detect. I installed DNAscent and all dependencies on an AWS instance running Ubuntu 16 according to the documentation. I made sure all files have full permissions. I keep getting errors saying that it's unable to open files. I thought this may be a VBZ compression issue, so I downloaded your published fast5 data from https://www.ebi.ac.uk/ena/browser/view/ERX4016778, and I'm still getting errors. I've gone through several re-installs but the issue continues. This is my command and the full error for the published data:

/Data1/software/DNAscent/bin/DNAscent index -f /Data1/pub/env/ig/atelier/nanopore/cns/MN17490/180226_MN17490_FAH59201_A/events/20180226_1219_1002/fast5/1

2023-05-30 11:24:04.622006: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-05-30 11:24:04.622080: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

terminate called after throwing an instance of 'IOerror'
  what():  Could not open file: 
Aborted (core dumped)

There absolutely are files in that directory, all with full permissions. Is there a better test dataset to run on, perhaps one with a sequencing summary file? I'm sure this is a simple error, and I apologize for redundancy with other issues. Nothing I've tried from other issue resolutions has worked for me so far. I would appreciate any help here.

Thank you,
Nick

**Comment by MBoemo** [comment]
Hi Nick, sorry to hear you're having trouble - can you just check this isn't a repeat of https://github.com/MBoemo/DNAscent/issues/19?

**Comment by MBoemo** [comment]
Closing for now, but reopen if that didn't fix it.

**Comment by ddubocan** [comment]
Hi,

I am running into the same issue.

All files have full permissions and I am using the full path.
I also received the same error.

When I use `--files= ` instead of '-f' the error changes to:

`Exiting with error.  Insufficient arguments passed to DNAscent index
`

Appreciate your help!

**Comment by MBoemo** [comment]
Can you let me know the sequencing platform (Flongle, MinION, GridION, or PromethION) you're using, the version of Guppy you used, and paste the first 20-ish lines of the sequencing summary file?

**Comment by ddubocan** [comment]
I appreciate the prompt response!
Using MiniON with R9.4 chemistry.

I wasn't aware that basecalling needed to be run first. I will basecall with guppy and let you know if that fixes the problem.

**Comment by MBoemo** [comment]
No problem - there's also a suggested workflow here: https://dnascent.readthedocs.io/en/latest/workflows.html

Closing for now but reopen if that doesn't fix it.
