### ISSUE TITLE
BrDU detection on R10.4.1 400bps run

### ISSUE THREAD

**Issue by Mathias-Boulanger** [MBoemo/DNAscent#36]
Hi,

Now that old Nanopore chemistry will be discontinued this year, is there a way to call BrDU on runs using the new R10.4.1 flow cells (GridION/PromethION)?
Do you plan to train DNAscent for the new chemistry?

Thank you for your help.

Best,
Mathias Boulanger
EMBL

**Comment by MBoemo** [comment]
Yes we're working on it - will be released soon.

**Comment by Mathias-Boulanger** [comment]
Amazing! thank you
