### ISSUE TITLE
fast5 files not recognized

### ISSUE THREAD

**Issue by MRMacArthur** [MBoemo/DNAscent#38]
I am trying to get DNAscent running and getting stuck on the index step. I am specifying the full path to the fast5 file directory and read summary file and am receiving the following 'This doesn't look like a fast5 file' error. 

I'm using reads generated on a MinION 9.4.1 flowcell with a recent release of MinKNOW. 

I've added the HDF5_PLUGIN_PATH to my bashrc and tried re-making the package. Do you have any tips for troubleshooting this.

This doesn't look like a fast5 file: -
- Ensure all files are decompressed.
- Use the --GridION flag if the sequencing summary file was generated by a GridION.
terminate called after throwing an instance of 'MissingFast5'
  what():  In specified directory, couldn't find fast5 file: -
/var/spool/slurmd/job50640695/slurm_script: line 10: 3124804 Aborted                 (core dumped) DNAscent index -f /scratch/gpfs/usr/NanoporeOutput/analogsBrdu/fast5/ -s /scratch/gpfs/usr/NanoporeOutput/analogsBrdu/sequencing_summary_FAS55048_9b6a2b5a_8b7a24c7.txt

**Comment by MBoemo** [comment]
Can you share a few things:
- the version of Guppy you used
- confirm that you saved files as FAST5 rather than POD5
- the first few lines of the sequencing summary

**Comment by MRMacArthur** [comment]
Many thanks for the quick reply.

Guppy version: Using MinKNOW (23.07.15) w/ Guppy 7.1.4

I am pretty certain the output is fast5, the file extension is .fast5 and the compression is described in the attached output report image.
![MinKNOW_report](https://github.com/MBoemo/DNAscent/assets/34972336/03517e6b-e6fc-4ccf-bd21-8a5d05fbb150)

Attaching screencap of head of sequencing summary.
![SeqSummary_head](https://github.com/MBoemo/DNAscent/assets/34972336/510e34e6-857f-413e-8bce-d1db09dbaaeb)

**Comment by MBoemo** [comment]
Looks like ONT have changed the format of the sequencing summary file with the latest Guppy release - thanks for bringing this to my attention. This should now be fixed in [commit d57082f](https://github.com/MBoemo/DNAscent/commit/d57082f35f7c3e9dab0ac61cc60510ee43ccac1e) where the default behaviour is to parse sequencing summary files in this new format. Old formats are still supported with the --legacy flag to DNAscent index. Just pull from master and recompile.

Closing for now, but reopen if that didn't fix it.

**Comment by MRMacArthur** [comment]
This solved the issue, thank you for solving so quickly.

For future readers newer to git, this update requires modifying the installation workflow to not specify version upon checkout (just `git checkout`)
