### ISSUE TITLE
Adapt DNAscent to POD5 new default on MinKNOW?

### ISSUE THREAD

**Issue by GeoMicroSoares** [MBoemo/DNAscent#39]
Hi there @MBoemo ,
Seems that ONT are setting the POD5 format as default (no FAST5 option) for sequencing run outputs - would adapting to this be something that's on your plans DNAscent? 
If not, we'd try and attain and keep an older version of MinKNOW to make sure DNAscent has everything it needs to run...

Best,

**Comment by MBoemo** [comment]
We're planning to support POD5 but this might not be ready in time for the first R10 release. In the meantime, you can convert pod5 to fast5: https://pypi.org/project/pod5/#:~:text=The%20pod5%20convert%20to_fast5%20tool,file%2Dread%2Dcount%20argument
