### ISSUE TITLE
GLIBCXX_3.4.20 not found

### ISSUE THREAD

**Issue by dariober** [MBoemo/DNAscent#4]
I compiled DNAscent (commit 39fd07c) as per documentation with:

```
git clone --recursive https://github.com/MBoemo/DNAscent.git
cd DNAscent/
make
```

When I try to execute it I get:

```
./bin/DNAscent 
./bin/DNAscent: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./bin/DNAscent)
./bin/DNAscent: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./bin/DNAscent)
```

This is with CentOS 7 and gcc version 8.2.0.

The workaround I used is to install libgcc with conda and set the LD_LIBRARY_PATH:

```
conda install libgcc # libgcc version 7.2.0 at present 

export LD_LIBRARY_PATH=${CONDA_PREFIX}/lib

## Now it seems ok:
./bin/DNAscent
DNAscent is a software tool for detecting regions of base analogue incorporation in Oxford Nanopore reads.
To run DNAscent, do: 
  ./DNAscent [executable] [arguments]
The executables that DNAscent can run are:
  --help
  -h
  detect
  index
  psl
  regions
```

Are there better solutions?

Thanks! Dario

**Comment by MBoemo** [comment]
That seems like a reasonable solution to me - have you had any trouble running the executables (index, detect, etc.)?

**Comment by dariober** [comment]
Hi- Thanks for the software and for getting back to me so quickly! I'm experimenting now with DNAscent and, no, no problem running the executables. (I may be back with more questions...)

**Comment by MBoemo** [comment]
No problem, just get in touch if you have any questions.
