### ISSUE TITLE
Running on a Nvidia A100 GPU

### ISSUE THREAD

**Issue by johnire80** [MBoemo/DNAscent#40]
Hello,

I am trying to run DNAscent on a cluster with Nvidia A100 GPUs.   Is this possible? 

DNAscent uses tensorflow 1.15x but, according to what I have read, the A100 can only use tensorflow 2x (the A100 needs cuda 11 & cudnn 8 which apparently cant use tensorflow 1.15x).

However, using tensorflow 2.4, cuda 11 & cudnn 8, I can get DNAscent running on a A100, but the results are strange, producing 2 floating point numbers rather than a float and sequence string (see below).   Does this suggest that minimal changes to DNAscent could  get it working with tensorflow 2.4?

#Alignment guppy_output_all/pass/alignment.sorted.bam
#Genome GCA_002163515.1_ASM216351v1_genomic.fa
#Index index.dnascent
#Threads 1
#Compute GPU
#Mode CNN
#MappingQuality 20
#MappingLength 200
#SystemStartTime 20/11/2023 15:18:10
#Software /dnascent/DNAscent/
#Version 3.1.2
#Commit d57082f35f7c3e9dab0ac61cc60510ee43ccac1e
>2057e48f-732b-4228-9560-fea0709f321a CM007964.1 0 306 fwd
>1f3a1973-3350-4b47-ba69-3e0e79f3a451 CM007964.1 0 303 fwd
>ed5096a0-d54f-4f5d-ab27-260e3444739c CM007964.1 0 305 fwd
>31cc4b53-81b9-41a5-afac-29e2c03f2615 CM007964.1 0 306 fwd
>f7a1e6cf-cbdb-470a-9c4d-746a48b8aa1e CM007964.1 0 303 fwd
>a2adcee3-91c0-449d-a653-a7e969e00afe CM007964.1 0 46253 fwd
306    0.040656    0.113539
309    0.064228    0.189773
315    0.046056    0.182314
320    0.039238    0.156609
<cut>

Regards,

John Ireland
__________________________
Institute of Genetics and Cancer
The University of Edinburgh

**Comment by MBoemo** [comment]
I think you're confusing v2 with v3. Version 2 only detects BrdU so the output is a read header followed by two columns (genome position on the left and probability of BrdU on the right). You're using v3.1.2 which detects BrdU and EdU, hence you get two probabilities (one for each analogue) at each genomic position.

3.1.2 uses Tensorflow 2.4.1 which we routinely run on A100s.

**Comment by johnire80** [comment]
Thanks for the quick response!
