### ISSUE TITLE
Slow speeds on GPUs with DNAscent detect on v4.0.1

### ISSUE THREAD

**Issue by MBoemo** [MBoemo/DNAscent#44]
We're aware that some users are experiencing speed issues on certain GPUs when running DNAscent detect in v4.0.1. We're working on a fix, but if you're also experiencing this issue, it would help us out if you can post what GPU you're using below.

**Comment by OsredekIvana** [comment]
Hi Michael! 
I am experiencing this issue, too. 
I am using the NVIDIA Tesla series, but we also have other options available, such as GeForce RTX 3090 and some AMD GPUs. Could you maybe share which GPU works better than the other one in the case of DNAScent? 
Thank you!

**Comment by MBoemo** [comment]
Resolved in commit https://github.com/MBoemo/DNAscent/commit/884bef1a73229abbe37594975ca4dee932244c0e.
