### ISSUE TITLE
Conversion into .bed file

### ISSUE THREAD

**Issue by OsredekIvana** [MBoemo/DNAscent#45]
Hello,

First of all, thank you for this amazing package! 
I have an issue with the dnascent2bedgraph.py for which I cannot see where is it coming from. I followed the proposed workflow and generated the output from DNAscent detect. However, when I run the py script as a next step, I get an error as follows:

 

<img width="1038" alt="Screenshot 2024-03-06 at 17 15 09" src="https://github.com/MBoemo/DNAscent/assets/157711817/fc74e893-7854-42e8-947a-f67a26ee8ed0">

Would you maybe have an idea on what may be causing this error?

Many thanks in advance!

**Comment by MBoemo** [comment]
Would you mind pasting the command you used?

**Comment by OsredekIvana** [comment]
Thank you for a quick reply!

Here is the command:

<img width="761" alt="Screenshot 2024-03-06 at 17 45 27" src="https://github.com/MBoemo/DNAscent/assets/157711817/6ee9ff84-579f-4b19-a660-b9e4cf420580">

**Comment by MBoemo** [comment]
This feels like the detect file may have been malformed in some way - can you think of anything you ran/moved that might have caused that?
