### ISSUE TITLE
Dorado pod5 version 

### ISSUE THREAD

**Issue by amireden** [MBoemo/DNAscent#47]
Hi,
Thank you for this tool. Before I start, I want to make sure I understand the situation: you include a per-release version with bascalling models for R10.4.1 5khz but currently the way to use them is only using Guppy on fast5 files (Pod5 should be converted to fast5). Is this correct?
You plan to issue a new version that will use Dorado. Would you advise to wait for the next version? or do you we will gain by becoming familiar with the current version. 
Many thanks,
amir

**Comment by MBoemo** [comment]
All correct. No reason to not start now - conversion between pod5 and fast5 is quite easy and quick.
