### ISSUE TITLE
DNAscent detect - Importing reference aborted

### ISSUE THREAD

**Issue by ThDef** [MBoemo/DNAscent#48]
Hi ! 

First of all, thank you for responsiveness for all the previous and closed issues. I am currently trying to use your tool and some of the help that you have provided to other people has helped me a lot too !

Now, here is my problem : 
- I am currently running the version 4.0.1 of DNAscent
- I have successfully produced an index.dnascent file for my data with the DNAscent index command
- I am trying to use the DNAscent detect subprogram through this command 

`DNAscent detect -b /path/to/my/alignment/file.sorted.bam -r /path/to/my/reference/genome.fasta -i index.dnascent -o chr1.detect -t 10`

The first few second seem to go well until the program reaches the "Importing the reference" step where it stops after saying "DNAscent: /path/to/reference.fasta: Empty sequence on line 1"
I tried to figure out if there was an issue with my genome file but everything seems okay, the first line is the first sequence header and it looks that there is no gap or problem with how the file is formated.
The path to the file is also okay with no mistakes in it.

I did not find any other issues that seems to have the same problem as me so here I am !

Thanks for your time and help

**Comment by MBoemo** [comment]
Just to check: When you write /path/to/reference.fasta, you're putting the real path in right? Not literally "/path/to/reference.fasta"?

**Comment by ThDef** [comment]
Yes, it is the absolute path to my file.

Le mer. 10 avr. 2024, 12:25, Michael A. Boemo ***@***.***> a
écrit :

**Comment by MBoemo** [comment]
Can you send me the reference file or a link to it so I can take a look (mb915@cam.ac.uk)?

**Comment by ThDef** [comment]
Sure ! Sending it to you right now

**Comment by MBoemo** [comment]
Whatever you used to generate this file was including Windows-style carriage return characters at the end of each fasta line. This was tripping an older version of the pfasta library that was parsing the reference. Should be resolved in [`commit 1d58647`](https://github.com/MBoemo/DNAscent/commit/1d58647d7b6cae50c7ecd75d1b792be1298b8bb5). Pull from master then `make clean && make`.
