### ISSUE TITLE
DNAscent index - program terminated prematurely

### ISSUE THREAD

**Issue by TeriCheng** [MBoemo/DNAscent#49]
Hi, 

Thank you very much for writing this tool! Excited to try this out especially now that it is compatible with R10 flow cells.

But I ran into an issue on the indexing part, where the program appeared to stop at 0%.

Here is the command I used (full path was used but masked for privacy):

`DNAscent index -f /grid/path/to/data/ -s /grid/path/to/data/sequencing_summary_PAOxxxxx_xxxxx_xxxxx.txt --GridION`

Within the `/grid/path/to/data` directory it contains the directories `fast5_pass`, `fast5_fail`, `fast5_skip`, `fastq_pass`, `fastq_fail`, among other reports and QC as generated by MinKNOW.

The output looked like this:
`[>                                  ]   0%      1/2179   4hr10min29sec`

And then it just terminated itself. Within the `index.dnascent` file it was a single line of:

`-       /grid/path/to/data/fast5_skip/PAOxxxxx_skip_xxxxx_xxxxx_0.fast5`.

Could it be the fast5_skip that was causing the problem? I tried specifying in the `-f` tag into either the `fast5_pass` or `fast5_fail` directories but the program would throw an error of not finding that single fast5 file in my fast5_skip directory. The data was generated using P2 Solo (hence the `--GridION` tag) and the MinKNOW version was `24.02.10`.

Thank you for your time and help!
Best,
Teri

**Comment by MBoemo** [comment]
Can you paste the first few lines of the sequencing summary file? Also when you say it terminated itself, did you see any sort of error message?

**Comment by TeriCheng** [comment]
Thank you for your quick response. When the program ended there was no error message. This is the first 3 lines of the sequencing summary file:

`filename_fastq	filename_fast5	filename_pod5	parent_read_id	read_id	run_id	channel	mux	minknow_events	start_time	duration	passes_filtering	template_start	num_events_template	template_duration	sequence_length_template	mean_qscore_template	strand_score_template	median_template	mad_template	pore_type	experiment_id	sample_id	end_reason	alias	type	barcode_arrangement	barcode_full_arrangement	barcode_kit	barcode_variant	barcode_score	barcode_front_id	barcode_front_score	barcode_front_refseq	barcode_front_foundseq	barcode_front_foundseq_length	barcode_front_begin_index	barcode_rear_id	barcode_rear_score	barcode_rear_refseq	barcode_rear_foundseq	barcode_rear_foundseq_length	barcode_rear_end_index
PAO90952_fail_unclassified_ef895f96_8ee9f05c_0.fastq.gz	PAO90952_fail_ef895f96_8ee9f05c_0.fast5	-	5b8bd192-156d-4373-bc15-328d18597447	5b8bd192-156d-4373-bc15-328d18597447	8ee9f05c0869b4c3de1e469d483243f2c3d335d1	1862	452	16.081400	0.738800	FALSE	16.083400	614	0.736800	1	2.000000	0.000000	-767.171814	0.007988	not_set	(experiment_id)	(sample_id)	signal_positive	unclassified	na	unclassified	NB01_var1	NB	var1	-40.000000	NB01_FWD	-40.000000	AGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCT	C	1	0	NB01_REV	-40.000000	GGTGCTGAAGAAAGTTGTCGGTGTCTTTGTGTTAACCTTAGCAAT	C	1	0
PAO90952_fail_unclassified_ef895f96_8ee9f05c_0.fastq.gz	PAO90952_fail_ef895f96_8ee9f05c_0.fast5	-	6556e8e7-1238-4bc5-95b9-98ab52dca8ff	6556e8e7-1238-4bc5-95b9-98ab52dca8ff	8ee9f05c0869b4c3de1e469d483243f2c3d335d1	2200	435	23.811000	0.648400	FALSE	23.813000	538	0.646400	13	3.730981	0.000000	-735.171814	0.007988	not_set	(experiment_id)	(sample_id)	signal_positive	unclassified	na	unclassified	NB06_var1	NB	var1	6.250000	NB06_FWD	6.250000	AGGTTAAGACTACTTTCTGCCTTTGCGAGAACAGCACCT	GAAGGCTTTGAAG	13	0	NB06_REV	-11.333333	GGTGCTGTTCTCGCAAAGGCAGAAAGTAGTCTTAACCTTAGCAAT	GAAGGCTTTGAA	12	1`

**Comment by MBoemo** [comment]
Looks like a different sequencing summary format being made by the P2 Solo - thanks for making me aware of this, I'll push a fix this evening.

**Comment by MBoemo** [comment]
This should be fixed in [commit b22307c](https://github.com/MBoemo/DNAscent/commit/b22307c562485453daa623b0c10a5e19f235169a). Just do the following: 
`git pull`
`make clean && make`
Then rerun DNAscent index with the new `--P2Solo` flag instead of the `--GridION` flag.
Would be grateful if you can confirm that this fixed it.

**Comment by TeriCheng** [comment]
Works now! Thank you for your prompt response.

**Comment by ThDef** [comment]
Hi ! It seems that I have the same kind of problem

I am currently using the v.3.1 of DNAscent because we are using leftovers R.9.4 flowcells but the index step seems also to stop prematurely resulting in a one line file :
```
#bulk
-	/generic/path/no_sample/20240517_0955_MC-114389_FAT83410_ad8b328a/Fast5/FAT83410_pass_ad8b328a_c733781b_21.fast5
```

The data was generated by MinKNOW v.24.02.16 with Dorado v.7.3.11 and my sequencing_summary looks the same as the one from this issue : 

```
filename_fastq	filename_fast5	filename_pod5	parent_read_id	read_id	run_id	channel	mux	minknow_events	start_time	duration	passes_filtering	template_start	num_events_template	template_duration	sequence_length_template	mean_qscore_template	strand_score_template	median_template	mad_template	pore_type	experiment_id	sample_id	end_reason	alias	type	barcode_arrangement	barcode_full_arrangement	barcode_kit	barcode_variant	barcode_score	barcode_front_id	barcode_front_score	barcode_front_refseq	barcode_front_foundseq	barcode_front_foundseq_length	barcode_front_begin_index	barcode_rear_id	barcode_rear_score	barcode_rear_refseq	barcode_rear_foundseq	barcode_rear_foundseq_length	barcode_rear_end_index
FAT83410_pass_barcode02_ad8b328a_c733781b_0.fastq.gz	FAT83410_pass_ad8b328a_c733781b_0.fast5	-	e39cdb31-60cd-47a3-ace0-0444fa7c1251	e39cdb31-60cd-47a3-ace0-0444fa7c1251	c733781badc5d1703389daa704a3f982a6b9d288	324	1	494	115.602000	2.237000	TRUE	115.694500	1715	2.144500	1074	9.828687	0.000000	77.607750	13.742680	not_set	20240517_cidb	no_sample	signal_negative	barcode02	test_sample	barcode02	RBK402	RBK4	n/a	99.166664	RBK02_FWD	99.166664	GCTTGGGTGTTTAACCTCGATTCCGTTTGTAGTCGTCTGTGTTTTCGCATTTATCGTGAAACGCTTTCGCGTTTTTCGTGCGCCGCTTCA	GATGGGTGTTTAACCTCGATTCCGTTTGTAGTCGTCTGTGTTTCGCATTTATCATTTCGCGTTTTACCGTGCATAACTTCA	81	16	-	-inf	-	-	0	151

```

If it is the same problem, would it be possible to update the V.3 of DNAscent so that it can work with this kind of sequencing summary ?

Thanks for your help,
