### ISSUE TITLE
Output file for index command

### ISSUE THREAD

**Issue by dariober** [MBoemo/DNAscent#5]
This is a small thing... It seems the subprogram `DNAscent index` (commit 39fd07c) is hard-coded to output to file `index.dnascent` which is a bit awkward if you have multiple samples. 

Would it be possible to add a `--output` option instead? Or just write to `stdout`?

Thanks! Dario

**Comment by MBoemo** [comment]
Yes I agree that could be inconvenient for some users.  I'm about to roll out a fairly big update in the next week or two, so I'll look at changing this as part of the update.
