### ISSUE TITLE
[Discussion] DNAscent as Conda Package and Hosting

### ISSUE THREAD

**Issue by ThDef** [MBoemo/DNAscent#50]
Hello,

I am currently designing a small pipeline for Brdu detection for my team and as such, I was wondering if you have any plan to host your tool as a conda package on any conda channel to facilitate installation and reproductibility ?
Having the option to easily set up a virtual environment with all the tools required at a specific version would be a big + for my team of biologists who are not really used to do any bioinformatics work.

Thanks for your time !
ThDef

**Comment by HrishiDhondge** [comment]
This can also help to address the issues raised in #51

**Comment by MBoemo** [comment]
@HrishiDhondge agreed - image is made, just testing over the next day or two and then I'll post it.

**Comment by HrishiDhondge** [comment]
@MBoemo, Thanks for quick response. I would be happy to test it (on different platform) in case you need a few more hands. 🙂

**Comment by MBoemo** [comment]
Here's a singularity image of our latest release: https://cloud.sylabs.io/library/mboemo/dnascent/dnascent
DNAscent documentation has been updated accordingly. Hope that helps!
