### ISSUE TITLE
Assertion `querySpan >= 0' failed

### ISSUE THREAD

**Issue by sathish-t** [MBoemo/DNAscent#53]
Hello,

A colleague and I have had the latest DNAscent (commit 18865e) process many reads on two different samples (32% and 97% respectively) and then fail with this error message. We did not run into this at any point while running DNAscent v2.

```
DNAscent: src/alignment.cpp:621: std::shared_ptr<AlignedRead> eventalign(read&, unsigned int, std::map<unsigned int, std::pair<double, double> >&): Assertion `querySpan >= 0' failed.
```

Based on the following lines in src/alignment.cpp, it occurs to me that windowLength - k + 1 could be <= 0 close to the end of the read which would trigger such an error but I am not sure ...

```
# Lines 544-546
//adjust so we can get the last bit of the read if it doesn't line up with the windows nicely
unsigned int basesToEnd = r.referenceSeqMappedTo.size() - posOnRef ;
unsigned int windowLength = std::min(basesToEnd, totalWindowLength);

# Lines 619-621
//flag large insertions
int querySpan = (r.refToQuery)[posOnRef + windowLength - k + 1] - (r.refToQuery)[posOnRef];
assert(querySpan >= 0);
```

Regards
Sathish

**Comment by MBoemo** [comment]
Thanks for pointing this out - should be fixed in https://github.com/MBoemo/DNAscent/commit/286d5ffb812211288b17cfb74e358f4a92689a4d but reopen if that doesn't fix it.
