### ISSUE TITLE
Error DNAscent detect

### ISSUE THREAD

**Issue by santoshbiowarrior333** [MBoemo/DNAscent#55]
Relink `/mnt/beegfs/esashi/Santosh/DNAscent/tensorflow/lib/libtensorflow_framework.so.2' with `/lib/x86_64-linux-gnu/libz.so.1' for IFUNC symbol `crc32_z'
Loading DNAscent index... ok.
Importing reference... ok.
Opening bam file... ok.
Scanning bam file...ok.
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 23090570368768:in 0sec  failed:      0  
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 550 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1872 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2902 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1357 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 298 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 402 in H5PL__find(): can't open directory
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
DNAscent: src/event_handling.cpp:637: void normaliseEvents(read&, bool): Assertion `et.n > 0' failed.
Aborted (core dumped)

**Comment by MBoemo** [comment]
Repeat of https://github.com/MBoemo/DNAscent/issues/53

**Comment by HrishiDhondge** [comment]
Hello @MBoemo, 
I am using the latest DNAscent singularity image to run the DNAscent tool. While running the DNAscent detect, I am getting the following error:

```
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 23453613315840:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
terminate called after throwing an instance of 'IOerror'
  what():  Could not open file: 
/mnt/beegfs/home/user/stageout/new_wf/DNAscent_data/dnascent_runner.sh: line 14: 1961913 Aborted 
```

From the HDF5-DIAG, it seems similar to this earlier detected issue. 
Do you think it's on the similar line?

Initially, I thought there might be issue with the format conversion from pod5 to fast5. But I also validated the fast5 files with HDF5 tools and the converted fast5 files are good.
Could you please help me to solve this issue?
Thanks in advance!

**Comment by MBoemo** [comment]
This usually arises when reads aren't indexed correctly. Did you run basecalling on the pod5 files or converted fast5 files? (It should be the latter.)

**Comment by HrishiDhondge** [comment]
Okay, got it. I used pod5 files for basecalling and it maybe the root cause for this error. I'll run the basecalling on converted fast5 files and then run the DNAscent. Thanks for the quick response!

**Comment by HrishiDhondge** [comment]
Hello @MBoemo, as per your instructions I ran basecalling on the converted fast5 files and used the bam file (after sorting and indexing) to call the DNAscent detect, and still gets the same error after some time:

```
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 23453650355968:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
terminate called after throwing an instance of 'IOerror'
  what():  Could not open file: 
/var/spool/slurm/d/job2785972/slurm_script: line 46: 2352496 Aborted                 
(core dumped)  singularity run --nv ${dnascent_sif} detect -b ${bam_file_sorted} -r ${reference_saccer} -i ${index_file} -o ${detect_output} -t 10 --GPU 0
```

I am using the singularity image provided latest version of DNAscent, 4.0.2. I used the following command for the DNAscent detect:
```
$ singularity run --nv DNAscent.sif detect -b <path_to_sorted_bam_file.bam> -r <path_to_reference_genome.fa> -i <path_to_DNAscent_index_file> -o <path_to_output_filename.detect> -t 10 --GPU 0
```

**Comment by MBoemo** [comment]
Can you paste the first few lines of the index?
