### ISSUE TITLE
RNAscent tool development?

### ISSUE THREAD

**Issue by MaestSi** [MBoemo/DNAscent#56]
Dear Michael,
thank you for developing this tool. I was wondering if you have any plans to extend this tool to the analysis of nascent RNA by means of pulse and chase experiments followed by Nanopore direct RNA sequencing. In fact, I would be interested in using this approach for studying RNA PolII stalling.
Thanks in advance,
Simone

**Comment by MBoemo** [comment]
Apologies for the late reply - drop me an Email at mb915@cam.ac.uk and we can discuss further.
