### ISSUE TITLE
--legacy not working

### ISSUE THREAD

**Issue by ywang285** [MBoemo/DNAscent#57]
Hi, I am using DNAscent 4.0.2 from singularity, and MinKNOW 23.04.5 and Guppy 6.5.7, generated .pod5 data from PromethION 24 using R10 flowcells. I have converted pod5 to fast5. Because I am using an older version of Guppy, I tried to use the --legacy flag, with below error

2024-08-15 01:24:14.061314: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
terminate called after throwing an instance of 'InvalidOption'
  what():  Invalid option passed: --legacy
/var/spool/slurmd/job51440557/slurm_script: line 29: 28248 Aborted                 singularity run $DNAscent_sif index -f $fast5_folder -s $sequencing_summary -o $fast5_folder/index.dnascent --legacy

If I don't add the --legacy flag, I got the same error as posted in https://github.com/MBoemo/DNAscent/issues/38.

Could you please help with the issue?
Thank you!

**Comment by MBoemo** [comment]
Yes we took the sequencing summary formatting flags out (see patch notes: https://dnascent.readthedocs.io/en/latest/releaseNotes.html#v4-0-2). DNAscent index should tune itself to whatever sequencing summary format you have, but it sounds like this isn't happening in this case. Can you post the first few lines of the sequencing summary file?

**Comment by ywang285** [comment]
Thanks for your reply! Please see below:
[sequencing_summary_PAO28984_5e2b2ba1_e463ac1a_first_few_lines.txt](https://github.com/user-attachments/files/16628895/sequencing_summary_PAO28984_5e2b2ba1_e463ac1a_first_few_lines.txt)

**Comment by MBoemo** [comment]
It looks like basecalling was done on the pod5 files. For v4.0.2, you would convert pod5 to fast5 first and then run basecalling on the fast5 files.

While that's a way forward for now, it's clunky and I apologise that we've been slower with pod5 support than we'd like to be. The good news is that we do have full Dorado/pod5/modbam support in a development version now which is in late testing. We'll keep it in testing for another week or so to make sure everything is on point and then release it (along with an image) as v4.0.3.

**Comment by ywang285** [comment]
Look forward to the new release!
