### ISSUE TITLE
DNAscent detect not providing output

### ISSUE THREAD

**Issue by PRiano-bio** [MBoemo/DNAscent#59]
Dear Michael,

First, thank you very much for creating such a valuable tool and for making it accessible to biologists like myself.

As a non-bioinformatician, I wanted to familiarize myself with your tool before generating my own data.  After installing DNAscent via Singularity, I attempted to run it using published data ([link to NCBI data](https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRX4952561&o=acc_s%3Aa)).

I basecalled the data with Guppy using the configuration: dna_r10.4.1_e8.2_400bps_5khz_hac.cfg.  Following your workflow on the wiki, I then generated SAM and BAM files.

After successfully running "DNAscent index," I attempted to use "DNAscent detect" with both CPU and GPU options.  However, in both cases, the program only generated a header file and did not proceed with further analysis.  Here is the output file content:

`#Alignment /storage/home/user/test.sorted `
`#Genome /storage/home/user/sacCer3.fa `
`#Index /storage/home/user/index.dnascent `
`#Threads 1 `
`#Compute CPU `
`#Mode CNN `
`#MappingQuality 20 `
`#MappingLength 1000 `
`#SystemStartTime 21/08/2024 14:25:29 `
`#Software /app/DNAscent/ `
`#Version 4.0.2 `
`#Commit 93d4558f4687cf96c1fa3baf785937a4f1817482 `

The command used to run "DNAscent detect" (with relative terminal output) is shown below:

`⌂2.39user dl385cpu3~└3singularity run DNAscent.sif detect -b ~/test-sorted.bam -r ~/sacCer3.fa -i ~/index.dnascent -o ~/output.detect`
`INFO:    underlay of /etc/localtime required more than 50 (79) bind mounts`
`2024-08-21 13:11:34.266394: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0`
`Loading DNAscent index... ok.`
`2024-08-21 13:11:35.916666: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set`
`2024-08-21 13:11:36.601558: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2195740000 Hz`
`Importing reference... ok.`
`Opening bam file... ok.`
`Scanning bam file...ok.`
`⌂2.39user dl385cpu3~└3`

I would greatly appreciate your assistance in understanding why "DNAscent detect" is not processing the data and only generating a header file.  I'm eager to use your tool with my own data once I can resolve this issue.

Thank you for your time and support.

**Comment by MBoemo** [comment]
Glad you're interested in using the software.

This issue looks like a mismatch between nanopore versions. If I understand correctly, you're using DNAscent v4.0.2 on data that was released with this paper (https://www.nature.com/articles/s41592-019-0394-y). This study was done on the older R9.4.1 nanopore and it also used BrdU only. The Guppy model and DNAscent version (v4.0.2) you've used are for the new and current R10.4.1 nanopore. The pores are quite different and hence required a big software update to make DNAscent compatible with R10. When we measure fork speed and origins, we also typically use sequential EdU and BrdU pulses.

Without making you read through all the documentation and patch notes, here's a quick guide to the DNAscent versions over the years:
- v1.0.0 and below: R9.4.1 pores, BrdU only, and HMM-based detection. Not worth using at this point.
- v2.0.2: R9.4.1 pores, BrdU only, neural network-based detection (what I suggest you use for this dataset)
- v3.1.2: R9.4.1 pores, detection of both BrdU and EdU in the same molecule, detects fork stalls
- v4.0.2: R10.4.1 pores, detection of both BrdU and EdU in the same molecule, detects fork stalls

**Comment by PRiano-bio** [comment]
Thank you so much for your prompt reply!

I had assumed that the new software might be somewhat compatible with data from previous chemistries, but it seems I was mistaken.

I was truly hoping to test the tool before generating my own data.  Would it be possible to add a small toy dataset to the repository for testing purposes?

I understand completely if this isn't feasible.  I just think it could be a valuable resource for others who might want to explore this tool without prior experience in nanopore sequencing.

Thank you again for your time and consideration.

**Comment by MBoemo** [comment]
We do generally try to make things back compatible but R9 --> R10 was a big change and making the software compatible with both would have resulted in a lot of bloat. Since R9 flow cells are now unavailable and the software is version controlled, we decided to just leave 3.1.2 as the last supported R9 version and move on. 

If you want EdU and BrdU labelling on R9 you could try our P. falciparum dataset with v3.1.2: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE210010

If you want EdU and BrdU labelling on R10 drop me a line (mb915@cam.ac.uk) and I'll send you some.
