### ISSUE TITLE
Overlapping kmers in `detect` output

### ISSUE THREAD

**Issue by dariober** [MBoemo/DNAscent#6]
Hello again- In the output of `DNAscent detect` I occasionally find overlapping kmers with high log-likelihood. For example this:

```
>00cc74c4-44aa-4132-86fe-c2b94afcf0c8 chrom.23 720931 765543 rev
...
724609  5.01598 CGCAAC  GCAAAC
724612  2.89642    AACATT  AACATT
...
```

I'm wondering if such cases can/should be considered as distinct BrdU sites or if I should collapse them in a single call to avoid double-counting them in downstream analysis. 

My understanding is that DNAscent cannot resolve BrdU at single nucleotide position, only at kmer resolution, so such cases may or may not be distinct events.

Any thought much appreciated - Thanks!
Dario

**Comment by MBoemo** [comment]
Sorry for the late reply.  DNAscent detect shows the log likelihood that BrdU was substituted for at least one T in the 6mer. In this case, the read maps to the reverse strand, so reverse complementing the third column shows that there's a T in the fourth position of the 6mer.  We found that BrdU tends to cause the biggest difference to the signal when it's at positions 3 and 4, so this is most likely two separate BrdUs.
