### ISSUE TITLE
DNAscent: src/event_handling.cpp:547: void normaliseEvents(DNAscent::read&, bool): Assertion `et.n > 0' failed.

### ISSUE THREAD

**Issue by ywang285** [MBoemo/DNAscent#62]
Hi, I installed version 4.0.3 by building from source because the Singularity image for 4.0.3 doesn't seem to be available yet.

I run the following commands:
eval "$(conda shell.bash hook)"
ml gcc/10.3.0
ml cuda/11.0.3 (if I use 11.1.1, libcusolver.so.10 will be failed to load)
module load math cudnn/8.1.1.33
conda activate DNAscent
DNAscent index -f $pod5_folder -o $pod5_fol
DNAscent detect -t $num_threads -b $bam_f -r $reference -i $pod5_folder/index.dnascent -o $bam_f.detect --GPU 0

However, I encounter the following error message:
DNAscent: src/event_handling.cpp:547: void normaliseEvents(DNAscent::read&, bool): Assertion `et.n > 0' failed.

Detailed stdout:
[DNAscent_test_ver20240904.txt](https://github.com/user-attachments/files/16883251/DNAscent_test_ver20240904.txt)

I’ve already downloaded and added the following line to my .bashrc file:
export HDF5_PLUGIN_PATH=/.../ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin 
But this hasn’t resolved the issue. 

Do you have any insights into what might be causing this error? Would it be better to wait for the Singularity image of version 4.0.3, which might address this?

Thanks in advance!

**Comment by MBoemo** [comment]
The fact that this seems to fail immediately is suspicious. You were previously using 4.0.2, correct? Did you have any similar issues there?

4.0.3 image isn't up yet because I'm travelling but will be soon.

**Comment by ywang285** [comment]
> The fact that this seems to fail immediately is suspicious. You were previously using 4.0.2, correct? Did you have any similar issues there?
> 
> 4.0.3 image isn't up yet because I'm travelling but will be soon.

I wasn't able to do the index with 4.0.2 because my data was called using dorado from pod5. Do you think it is possible that HDF5_PLUGIN_PATH isn't really functioning and that caused this problem (because the error I encountered is very similar to [this post](https://www.biostars.org/p/9504758/), although I am working on pod5 not fast5)? Is there a way to check that?

**Comment by ywang285** [comment]
Thanks for uploading 4.0.3 image. I tried running DNAscent from the image and I got the same error message.

**Comment by MBoemo** [comment]
My guess is still that the software isn't finding the POD5 files correctly on your filesystem (i.e., an indexing issue). Can you post the stderr and first few lines of the index (indexed with v4.0.3)?

**Comment by ywang285** [comment]
Sure, here are stderr, stdout, and the first few lines of indexed by 4.0.3:
[DNAscent_test_ver20240904.out.txt](https://github.com/user-attachments/files/16935576/DNAscent_test_ver20240904.out.txt)
[DNAscent_test_ver20240904.err.txt](https://github.com/user-attachments/files/16935517/DNAscent_test_ver20240904.err.txt)
[index_first_few_lines.dnascent.txt](https://github.com/user-attachments/files/16935571/index_first_few_lines.dnascent.txt)

**Comment by ywang285** [comment]
It seems I’ve identified the issue: the BAM file I’m using contains four additional tags—ns, nl, as, and al—which were added by the add-nucleosomes command from [fibertools-rs](https://github.com/fiberseq/fibertools-rs?tab=readme-ov-file). When I use a BAM file directly from Dorado, without processing by fibertools-rs, the error message no longer appears. I'm not sure why, but it seems these tags are causing conflicts with DNAscent detect?

**Comment by MBoemo** [comment]
From what I can gather, the issue here seems to be the ns tag. Dorado adds an ns tag which DNAscent uses (https://github.com/nanoporetech/dorado/blob/9ac85c65fc873a956bda00b2f5608b2bf72d9e7c/documentation/SAM.md?plain=1#L30). From this page (https://fiberseq.github.io/fiberseq-bam.html?highlight=ns#the-fiber-seq-bam-format) of the documentation, fibertools-rs seems to be using the ns tag not for a number of signals (as Dorado does) but for nucleosome positioning. You should probably contact the developers about this as it can lead to unexpected downstream behaviour and conflicts (as it has here).

**Comment by ywang285** [comment]
> From what I can gather, the issue here seems to be the ns tag. Dorado adds an ns tag which DNAscent uses (https://github.com/nanoporetech/dorado/blob/9ac85c65fc873a956bda00b2f5608b2bf72d9e7c/documentation/SAM.md?plain=1#L30). From this page (https://fiberseq.github.io/fiberseq-bam.html?highlight=ns#the-fiber-seq-bam-format) of the documentation, fibertools-rs seems to be using the ns tag not for a number of signals (as Dorado does) but for nucleosome positioning. You should probably contact the developers about this as it can lead to unexpected downstream behavior and conflicts (as it has here).

Thank you so much for your reply! It is good to know that DNAscent are actually using the ns tag added by Dorado but the tag is modified by fibertools-rs.
