### ISSUE TITLE
No EdU/BrdU incorporation detected in positive samples [100% "failed" detect and forksense and all "0"s in output file]

### ISSUE THREAD

**Issue by PRiano-bio** [MBoemo/DNAscent#63]
I sequenced with Nanopore (latest 10.4 flowcell) DNA samples that resulted positive for BrdU and EdU incorporation via immunoblot.
After running DNAscent 4.0.3 via Singularity, the output of forksense consists in one single read with just 0s for EdU and BrdU value. 
Moreover in the terminal output, both DNAscent detect and DNAscent forksense have 100% of "failed".
Here below I reported the reduced version of the output files and the output of the terminal. 

**TERMINAL OUTPUT:**
Even if the terminal output reported is truncated, there were no value other that "failed".
```
Processing sample: Test
Indexing BAM file...
All steps completed successfully for sample Test
Running DNAscent index step...
[========>                          ]  25%   1/4   0hr 0min 0sec  
[=================>                 ]  50%   2/4   0hr 0min 0sec  
[==========================>        ]  75%   3/4   0hr 0min 0sec  
[===================================] 100%   4/4   0hr 0min 0sec  
Running DNAscent detect step...
Loading DNAscent index... ok.
Importing reference... ok.
Opening bam file... ok.
Scanning bam file...ok.
[>                                  ]   0%      0/3639   0hr 0min 0sec  failed:     0  
[>                                  ]   0%      0/3639   0hr 0min 0sec  failed:     0  
[>                                  ]   0%      0/3639   0hr 0min 0sec  failed:     0  
[...]
[==================================>]  99%   3632/3639   0hr 0min 2sec  failed:   471  
[==================================>]  99%   3632/3639   0hr 0min 2sec  failed:   471  
[===================================] 100%   3639/3639   0hr 0min 0sec  failed:   478  
Running DNAscent forksense step...
[>                                  ]   0%      1/3161   0hr 0min 0sec  failed:     0  
[>                                  ]   0%      2/3161   0hr 0min 0sec  failed:     1  
[>                                  ]   0%      3/3161   0hr 0min 1sec  failed:     2  
[...]
[==================================>]  99%   3159/3161   0hr 0min 0sec  failed:  3031  
[==================================>]  99%   3160/3161   0hr 0min 0sec  failed:  3032  
[===================================] 100%   3161/3161   0hr 0min 0sec  failed:  3033  
Finished processing sample: Test
All samples processed. Job finished at Mon Sep  9 02:29:50 PM CEST 2024
```

1. **OUTPUT.DETECT :**
```
#Alignment /storage/home/user/dnascent-output/Test.sorted.bam
#Genome /storage/home/user/reference.fasta
#Index /storage/home/user/dnascent-output/Test.index.dnascent
#Threads 1
#Compute GPU
#Mode CNN
#MappingQuality 20
#MappingLength 1000
#SystemStartTime 09/09/2024 14:10:45
#Software /app/DNAscent/
#Version 4.0.3
#Commit 9f3ef31b58cb12a35795d31ebd42b97e6d8de890
>14864159-7402-4a4c-976a-ae5326137b92 reference 0 2397 fwd
10	0.064936	0.038356	GTGCTGCAA
20	0.127683	0.071554	GCGATTAAG
21	0.099561	0.048271	CGATTAAGT
25	0.129081	0.079023	TAAGTTGGG
26	0.117107	0.092562	AAGTTGGGT
[...]
2390	0.016510	0.034979	TTGTTTAGT
2391	0.019896	0.054742	TGTTTAGTT
```
TERMINAL OUTPUT:
```
2024-09-09 14:29:44.603341: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Estimated fraction of BrdU substitution in BrdU-positive regions: 0.271571
Estimated BrdU substitution lower bound in BrdU-positive regions: 0.189627
Estimated fraction of EdU substitution in EdU-positive regions: 0.127939
Estimated EdU substitution lower bound in EdU-positive regions: 0.0681818

```

2. **OUTPUT.FORKSENSE:**
Even if the file reported is truncated, no value different from 0 are present in the file.
```
#DetectFile /storage/home/user/dnascent-output/Test.output.detect
#Threads 1
#Compute CPU
#SystemStartTime 09/09/2024 14:29:47
#Software /app/DNAscent/
#Version 4.0.3
#Commit 9f3ef31b58cb12a35795d31ebd42b97e6d8de890
#EstimatedRegionBrdU 0.271571
#EstimatedRegionEdU 0.127939
>0b022afb-d4e1-4974-8dee-355a6ad0f4e2 Telnn.lin 0 5211 rev
4	0	0
13	0	0
14	0	0
[...]
7922	0	0
7937	0	0
7944	0	0
```

**Comment by MBoemo** [comment]
Hard to say - there are quite a few reasons this could happen based on your experimental setup. I'd need a lot more information on what you did on the wet lab side. Feel free to Email me at mb915@cam.cam.ac.uk to discuss if that's easier.

**Comment by PRiano-bio** [comment]
Dear Michael,

Thank you for your prompt response to my GitHub issue regarding DNAscent. I
appreciate your willingness to assist.

To provide more context for my experiment, I've outlined the wet-lab
procedures below:

*Cell Culture and Labeling:*

   - HEK293T cells were sequentially pulsed with 50µM EdU (5 minutes) and
   100µM BrdU (10 minutes).
   - Cells were washed twice with PBS between pulses.
   - Cells were harvested by scraping, lysed, and gDNA extracted using
   phenol-chloroform.

*DNA Analysis and Library Preparation:*

   - A dilution of gDNA was spotted on a membrane and probed with anti-BrdU
   antibodies to detect BrdU incorporation.
   - An EdU click-it reaction was performed to visualize EdU incorporation.
   - Negative controls showed no signal, confirming the specificity of the
   labeling.
   - A transposon-based kit was used to generate a library for sequencing
   on a MinION machine.

*Data Analysis:*

   - Basecalling and mapping of reads were performed using Dorado software.
   - DNAscent was run following the workflow outlined in the tool
   documentation.

As mentioned in the Github issue, I'm encountering some difficulties with
DNAscent outputs and I would be grateful for your insights into potential
causes or troubleshooting steps.I am really looking forward to move from
Molecular DNA Combing analysis to sequencing analysis using your great tool.

Thank you for your time and assistance.

Best regards,

Lorenzo Piano

Il giorno lun 9 set 2024 alle ore 17:33 Michael A. Boemo <
***@***.***> ha scritto:

**Comment by PRiano-bio** [comment]
I sent you an email, thanks a lot for the availability!
