### ISSUE TITLE
"Model configuration failed." and DNAscent detect analysis speed on GPU

### ISSUE THREAD

**Issue by ywang285** [MBoemo/DNAscent#64]
Hi, I am running DNAscent detect with 32 CPUs and 250 GB of memory. I noticed that using -t 256 significantly speeds up the process compared to using -t 32 or -t 128. However, when I set -t 256, I encountered the message: "Model configuration failed." Could you please advise if it is safe to ignore this warning? 

Additionally, what would be the optimal thread count for running DNAscent detect with 32 CPUs and 250 GB of memory? With -t 256, it predicts 375 hours to finish processing the BAM file:
[>                                  ]   0%     28234/9771746  375hr 2min58sec  failed:      602  

I also tested DNAscent detect on another compute node with 32 CPUs and 1x NVIDIA A100-SXM4-80GB GPU, using -t 64 (somehow I cannot go above 64 threads on this node), and found the analysis speed to be similar to the above pure 32 CPU configuration:
[>                                  ]   0%      5960/7997484  324hr 6min59sec  failed:      117
The output file indicates DNAscent is indeed using the GPU: 
[DNAscent_ver20240911_20240811_SNU16m1_EdU_BrdU_tubeB.err.txt](https://github.com/user-attachments/files/16964453/DNAscent_ver20240911_20240811_SNU16m1_EdU_BrdU_tubeB.err.txt)

  
Is this analysis speed expected?

Thank you so much in advance!

**Comment by MBoemo** [comment]
That's pretty extreme overthreading if you only have 32 CPUs available. The speed changes you're seeing are likely to do with how the size of the buffer changes (i.e., how many reads are loaded into memory at a time) according to how many threads are used. What's optimal will be different for each system so it's hard to say. Probably a case of "try it and see" as you have done.
