### ISSUE TITLE
Make error: missing library

### ISSUE THREAD

**Issue by ShephC** [MBoemo/DNAscent#65]
Trying to get 4.0.3 up and running and am encountering issues compiling. I'm attempting to make in a miniconda environment as a workaround for not having admin privileges. I've also tried building pod5 from the source with no luck. Any clue why? Here's the last few lines: 

`/usr/bin/ld: cannot find -lpod5_format
/usr/bin/ld: /u/cshepherd/DNAscent/pod5-file-format/build/third_party/libs/libjemalloc_pic.a(jemalloc.pic.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /u/cshepherd/DNAscent/pod5-file-format/build/third_party/libs/libjemalloc_pic.a(jemalloc.pic.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /u/cshepherd/DNAscent/pod5-file-format/build/third_party/libs/libjemalloc_pic.a(jemalloc.pic.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /u/cshepherd/DNAscent/pod5-file-format/build/third_party/libs/libjemalloc_pic.a(jemalloc.pic.o): unable to initialize decompress status for section .debug_info
/u/cshepherd/DNAscent/pod5-file-format/build/third_party/libs/libjemalloc_pic.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
make: *** [Makefile:127: bin/DNAscent] Error 1`

Thanks!

**Comment by MBoemo** [comment]
Looks like pod5 didn't build correctly - suggest going back through the error messages to figure out why or just use the singularity image that we provide.
