### ISSUE TITLE
Very low percent of reads have predominant BrdU probability > 0.5

### ISSUE THREAD

**Issue by ywang285** [MBoemo/DNAscent#69]
Hi, 
I treated cells expressing FUCCI with 50 µM EdU for 5 minutes, followed by 50 µM BrdU for 30 minutes, and then sorted the cells into early S and late S phases. Since the .detect file contains the probability of each basecalled T being EdU or BrdU in each read, I calculated the 50th percentile of the BrdU probability for each read (i.e., I stored the BrdU probabilities for a read as a list, then calculated np.percentile(probBrdU_list, 50) as the 50th percentile of the BrdU probability for the read) and created histograms for the reads from early S and late S cells:
![20240826_COLO320DM_FUCCI_TubeF_lateS barcode01 hg38_analysisSet_Dorado_aligner_default sorted amplicon_reads DNAscent_detect_out_BrdU_50_percentile_distribution](https://github.com/user-attachments/assets/7b78d737-42f2-422b-a159-2cea6bc3974c)
Here’s a zoomed-out view of the plot:
![image](https://github.com/user-attachments/assets/21e00618-b079-466b-821e-6e834870781e)

I found that only 0.1% of reads have a 50th percentile BrdU probability > 0.5. The N50 of the read length is 17 kb (I extracted the DNA using the MagAttract HMW DNA Kit and prepared the library using SQK-LSK114), which suggests that the majority of replicating DNA reads should have BrdU incorporated across the entire read. In principle, with a 30-minute labeling period during an 8-hour S phase, ~6% of the DNA should be replicating.

My questions are:
1. Why is the percentage of replicating DNA (i.e., 50th percentile BrdU probability > 0.5) so low?
2. What is the population of reads with a 50th percentile BrdU probability in the range of 0.075 to 0.2? I’ve attached IGV snapshots with base modification likelihood thresholds set to 0.1 and 0.5, where "5caU" (i.e., BrdU) is in green. For the reads with most BrdU probabilities above 0.1 but below 0.5, could they still represent replicating DNA?
Modbase threshold 0.1:
![igv_snapshot_threshold_0 1](https://github.com/user-attachments/assets/7bdf5c5e-7977-48e9-a126-f608af9eb2e4)
Modbase threshold 0.5:
![igv_snapshot_threshold_0 5](https://github.com/user-attachments/assets/431c32db-9b97-45da-85c0-b1263c969aa2)
3. What is the recommended way to classify reads as "replicating" or "non-replicating"?

Thank you so much in advance!

**Comment by MBoemo** [comment]
This is the behaviour I would expect. To understand why, imagine you have a 50 kb read which has a 20 kb fork track on it. Right off the bat, 60% of the calls are going to have a very low analogue probability because they're not in the fork track. Then suppose you have about 50% analogue-for-T substitution in your 20 kb fork track. That then gets you to 80% of the calls on the read having a low analogue probability (hence your low median) but it doesn't mean there's no fork there. To classify reads as replicating or non-replicating, use the forkSense executable which we provide for this purpose.

If you want to measure fork speed or stalling, two 30-min pulses are quite a bit too long for an N50 of 17 kb. Most of your fork calls are going to run off the molecule and you're probably going to see a lot of reads with only one analogue incorporated across them (which won't be called as a fork by forkSense).

**Comment by ywang285** [comment]
> This is the behaviour I would expect. To understand why, imagine you have a 50 kb read which has a 20 kb fork track on it. Right off the bat, 60% of the calls are going to have a very low analogue probability because they're not in the fork track. Then suppose you have about 50% analogue-for-T substitution in your 20 kb fork track. That then gets you to 80% of the calls on the read having a low analogue probability (hence your low median) but it doesn't mean there's no fork there. To classify reads as replicating or non-replicating, use the forkSense executable which we provide for this purpose.
> 
> If you want to measure fork speed or stalling, two 30-min pulses are quite a bit too long for an N50 of 17 kb. Most of your fork calls are going to run off the molecule and you're probably going to see a lot of reads with only one analogue incorporated across them (which won't be called as a fork by forkSense).

Just want to ensure my understanding is correct. For the reads shown in my IGV screenshot, which display large patches of 'light green' color (i.e., where most Ts in the read have a BrdU probability greater than 0.075 but less than 0.2):
![image](https://github.com/user-attachments/assets/b6f1257a-b264-4663-abd9-45e6584bb8ba)
Should I interpret this as these reads have many BrdU incorporations during the 30-minute labeling period? I ask because, according to the [documentation](https://dnascent.readthedocs.io/en/latest/visualisation.html), it seems that only BrdU probabilities greater than 0.5 are considered reliable.

**Comment by MBoemo** [comment]
Yes, I would use > 0.5 as a threshold for most applications. That said, it shouldn't be too sensitive to the threshold you pick as long as it's close - so any threshold in the [0.3, 0.7] region should give you a similar answer. I would say 0.2 is too low.

**Comment by ywang285** [comment]
> Yes, I would use > 0.5 as a threshold for most applications. That said, it shouldn't be too sensitive to the threshold you pick as long as it's close - so any threshold in the [0.3, 0.7] region should give you a similar answer. I would say 0.2 is too low.

Thank you for your reply! May I ask if you have estimated the false positive/negative detection rate of BrdU and EdU when setting threshold in the [0.3, 0.7] region? Which one is better if I only care about a single analogue incorporation (i.e., I only care about whether the DNA was replicated or not during the labeling period).

**Comment by MBoemo** [comment]
Roughly (as this might change a bit depending on the data you're using for benchmarking): false positive rate should be about 1/1000 thymidines for completely unlabelled DNA, and false negatives should be higher with rate of 0.1-0.2. I would expect a higher rate of false negatives when the analogue incorporation is particularly high.

**Comment by ywang285** [comment]
> Roughly (as this might change a bit depending on the data you're using for benchmarking): false positive rate should be about 1/1000 thymidines for completely unlabelled DNA, and false negatives should be higher with rate of 0.1-0.2. I would expect a higher rate of false negatives when the analogue incorporation is particularly high.

Thank you for the information! Does this mean that a high concentration of analogue treatment, which results in nearly all thymidine being substituted with BrdU or EdU, might also be problematic for DNAscent detect? I am also concerned that very high analogue incorporation could reduce Dorado's basecalling accuracy and consequently affect mapping. Could that be possible? Do you have any recommended concentration ranges for BrdU and EdU treatment with cultured cells to achieve optimal analogue incorporation for DNAscent detect?
