### ISSUE TITLE
DNAscent: detect

### ISSUE THREAD

**Issue by hcheng78** [MBoemo/DNAscent#7]
I'm having trouble with executing the detect command. I used the index command without a summary.txt file, is that the reason for it? I don't understand how to fix the errors that are popping up.

Loading DNAscent index... ok.
Importing reference... ok.
Opening bam file... ok.
Scanning bam file...ok.
[>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  [>                                  ]   0%       0/25236  
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140499451968512:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
terminate called after throwing an instance of 'HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140499383666432:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
terminate called recursively
Aborted (core dumped)

**Comment by MBoemo** [comment]
This arises when DNAscent can't find the fast5 files associated with the run.  Have you tried running it passing the sequencing summary file to DNAscent index?  Also can I just double check that you haven't moved the fast5 files on the filesystem since running DNAscent index previously?

**Comment by hcheng78** [comment]
I just ran it with the sequencing summary and its working now. Thank you so much for your help.

**Comment by MBoemo** [comment]
Great.  I'll try to reproduce this error today and look into why it was causing an issue.  Running with the sequencing summary is much faster, but it should still work either way.
