### ISSUE TITLE
Fail to open pod5 files for indexing, version 4.0.3

### ISSUE THREAD

**Issue by musikutiv** [MBoemo/DNAscent#71]
I have problems getting DNAscent to run for detecting BrdU. 
same problem for different runs on FLO-MIN114

> DNAscent index -f ${POD_PATH}
Failed to query batch count: Invalid: null file passed to C API
terminate called after throwing an instance of 'BadPod5Field'
  what():  pod5 field could not be opened.

> pod5 recover ${POD_PATH}
None of the 4 files given need recovery

anything I can do to solve the problem, do you have test pod5 files to test if there is a problem with my executable that I compiled from source?

**Comment by MBoemo** [comment]
Could be a problem with your compilation but my bet would be permissions and/or paths. POD5 files have been submitted here and are still being processed, but they should be publicly available in the coming days. https://www.ebi.ac.uk/ena/browser/view/PRJEB80561

**Comment by musikutiv** [comment]
thanks for the quick reply, that helped me to identify the problem: the pod5 directory contained hidden files ._*.pod5 that caused the problem. after  rm ._* everything is fine.

**Comment by MBoemo** [comment]
Great! Give a shout if you run into any other problems.
