### ISSUE TITLE
BrdU/EdU calling in highly methylated environments

### ISSUE THREAD

**Issue by JuandeBarba** [MBoemo/DNAscent#73]
Hi Michael and the team,

thanks a lot for the tool and for the recent update to 4.0.3. I am currently working with heavily 5mCG methylated DNA samples (in vitro methylation) and I was planning to analyze BrdU/EdU on the same reads. However, I was wondering if the calling of BrdU/EdU is affected by 5mC (or viceversa) and if I should take any precautions during analysis.

Thanks a lot for the time!

**Comment by JuandeBarba** [comment]
Just precisions, if they are useful, I am using R10 and performing the basecalling with Dorado v7 using the High Accuracy model for 5m in CG context.

**Comment by MBoemo** [comment]
Should be okay in theory - the model was trained on methylated DNA. But I'd recommend an extra layer of scrutiny for whatever the results are.
