### ISSUE TITLE
Does DNAscent handle supplementary alignments the same as primary alignments?

### ISSUE THREAD

**Issue by ywang285** [MBoemo/DNAscent#74]
Hi, I am working on a bam file in which each read has on average 20 supplementary alignments. I found somehow MM ML tags in supplementary alignments cannot be correctly handled by dorado aligner default setting, but below minimap2 alignment command seems work:
`minimap2 -x map-ont -a -t ${num_threads} -y --secondary=no -Y ${REFERENCE}
`
I wonder if I use a bam file aligned using the above command as DNAscent detect input, would there be any issue you can foresee? Thanks!

**Comment by MBoemo** [comment]
Sorry for the late reply. Just to check my understanding: you don't want to use these secondary alignments, hence why you're suppressing them with `--secondary=no`? If that's correct then there shouldn't be any issues.
