### ISSUE TITLE
An error with compilation

### ISSUE THREAD

**Issue by hasindu2008** [MBoemo/DNAscent#75]
Hello,

I tried to compile DNAscent following the instructions listed here: https://github.com/MBoemo/DNAscent?tab=readme-ov-file#building-from-source. Unfortunately, I am not able to use singularity in this case, so that is not an option. 

The compilation ran smoothly for like 10 minutes, but then gave me the following error:
```

Installing (downloading, building) binaries...

echo "const char *gitcommit = \"5bc32791ee3f57d78734b685bd9b24ceba52dff6\";" > src/gitcommit.h
echo "const char *executablePath = \"/home/hasindu/DNAscent/\";" > src/softwarepath.h
rm -f ./.depend
g++ -Wall -O2 -fopenmp -std=c++14 -I./hdf5-1.8.14/hdf5/include -I./htslib -I./fast5/include -I./tensorflow/include -I./pod5-file-format/build/c++ -MM  src/htsInterface.cpp src/forkSense.cpp src/data_IO.cpp src/reads.cpp src/trainGMM.cpp src/tensor.cpp src/detect.cpp src/trainCNN.cpp src/index.cpp src/event_handling.cpp src/fast5.cpp src/alignment.cpp src/common.cpp src/pod5.cpp src/probability.cpp          src/scrappie/event_detection.c src/scrappie/scrappie_common.c  src/pfasta/pfasta.c   > ./.depend;
In file included from src/detect.cpp:28:0:
src/../pod5-file-format/c++/pod5_format/c_api.h:3:10: fatal error: pod5_format/pod5_format_export.h: No such file or directory
 #include "pod5_format/pod5_format_export.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/trainCNN.cpp:22:0:
src/../pod5-file-format/c++/pod5_format/c_api.h:3:10: fatal error: pod5_format/pod5_format_export.h: No such file or directory
 #include "pod5_format/pod5_format_export.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/alignment.cpp:21:0:
src/../pod5-file-format/c++/pod5_format/c_api.h:3:10: fatal error: pod5_format/pod5_format_export.h: No such file or directory
 #include "pod5_format/pod5_format_export.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/pod5.cpp:12:0:
src/../pod5-file-format/c++/pod5_format/c_api.h:3:10: fatal error: pod5_format/pod5_format_export.h: No such file or directory
 #include "pod5_format/pod5_format_export.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:112: recipe for target '.depend' failed
make: *** [.depend] Error 1
```

I have that file which the error message says though:
```
~/DNAscent$ ls -lh src/../pod5-file-format/c++/pod5_format/c_api.h
-rw-rw-r-- 1 hasindu hasindu 34K Oct 31 17:28 src/../pod5-file-format/c++/pod5_format/c_api.h
```

Some help will be appreciated.

**Comment by MBoemo** [comment]
Looks like pod5 didn't compile correctly - there should be an error message further up that gives some indication of why. The C API header file will still be present even if the compilation fails.

**Comment by hasindu2008** [comment]
Hello

Thank you very much for the response. I am a still a bit confused though.

The error message above said ": fatal error: pod5_format/pod5_format_export.h: No such file or directory". But that file seems to be already available. So do you mean that this error message is incorrect and there should be another error message earlier?

Before the error message I copy paste above, I remember a warning from conan about the c++17, but wasn't an error.   I can double check. 

Is there an option to disable pod5 compilation and proceed with fast5 only? The hdf5 seemed to compile without an error. Or is fast5 much slower than pod5 and thus pod5 is recommended? 

Regards

**Comment by MBoemo** [comment]
As a test, I'd try compiling pod5 on its own and make sure that works as expected. Not an option to proceed with fast5 compilation only I'm afraid as it would be hard to disentangle the two.

**Comment by Elizabeth-mqz-gmz** [comment]
Hello!

I am having the exact same problem. I just tried installing manually [pod5](https://pod5-file-format.readthedocs.io/en/latest/) using `pip`, and everything was successfully installed from that side. But then I am trying to compile DNAscent again using `make`, and still get the same error. 

Did you manage to solve it?

```
thrift/0.20.0: ERROR: Package '249bff54fc55cab7da11f255d70827c83fc2b2b4' build failed
thrift/0.20.0: WARN: Build folder ~/.conan/data/thrift/0.20.0/_/_/build/249bff54fc55cab7da11f255d70827c83fc2b2b4/build/Release
ERROR: thrift/0.20.0: Error in build() method, line 123
        cmake.configure()
        ConanException: Error 127 while executing cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="~/.conan/data/thrift/0.20.0/_/_/build/249bff54fc55cab7da11f255d70827c83fc2b2b4/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="~/.conan/data/thrift/0.20.0/_/_/package/249bff54fc55cab7da11f255d70827c83fc2b2b4" -DCMAKE_POLICY_DEFAULT_CMP0074="NEW" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "~/.conan/data/thrift/0.20.0/_/_/build/249bff54fc55cab7da11f255d70827c83fc2b2b4/src"
rm -f ./.depend
g++ -Wall -O2 -fopenmp -std=c++14 -I./hdf5-1.8.14/hdf5/include -I./htslib -I./fast5/include -I./tensorflow/include -I./pod5-file-format/build/c++ -MM  src/alignment.cpp src/common.cpp src/data_IO.cpp src/detect.cpp src/event_handling.cpp src/fast5.cpp src/forkSense.cpp src/htsInterface.cpp src/index.cpp src/pod5.cpp src/probability.cpp src/reads.cpp src/tensor.cpp src/trainCNN.cpp src/trainGMM.cpp          src/scrappie/event_detection.c src/scrappie/scrappie_common.c  src/pfasta/pfasta.c   > ./.depend;
In file included from src/alignment.cpp:21:
src/../pod5-file-format/c++/pod5_format/c_api.h:3:10: fatal error: pod5_format/pod5_format_export.h: No such file or directory
    3 | #include "pod5_format/pod5_format_export.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/detect.cpp:28:
src/../pod5-file-format/c++/pod5_format/c_api.h:3:10: fatal error: pod5_format/pod5_format_export.h: No such file or directory
    3 | #include "pod5_format/pod5_format_export.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/pod5.cpp:12:
src/../pod5-file-format/c++/pod5_format/c_api.h:3:10: fatal error: pod5_format/pod5_format_export.h: No such file or directory
    3 | #include "pod5_format/pod5_format_export.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/trainCNN.cpp:22:
src/../pod5-file-format/c++/pod5_format/c_api.h:3:10: fatal error: pod5_format/pod5_format_export.h: No such file or directory
    3 | #include "pod5_format/pod5_format_export.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:113: .depend] Error 1
```

**Comment by MBoemo** [comment]
This will be the issue:

`thrift/0.20.0: ERROR: Package '249bff54fc55cab7da11f255d70827c83fc2b2b4' build failed
thrift/0.20.0: WARN: Build folder ~/.conan/data/thrift/0.20.0/_/_/build/249bff54fc55cab7da11f255d70827c83fc2b2b4/build/Release
ERROR: thrift/0.20.0: Error in build() method, line 123
        cmake.configure()
        ConanException: Error 127 while executing cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="~/.conan/data/thrift/0.20.0/_/_/build/249bff54fc55cab7da11f255d70827c83fc2b2b4/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="~/.conan/data/thrift/0.20.0/_/_/package/249bff54fc55cab7da11f255d70827c83fc2b2b4" -DCMAKE_POLICY_DEFAULT_CMP0074="NEW" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "~/.conan/data/thrift/0.20.0/_/_/build/249bff54fc55cab7da11f255d70827c83fc2b2b4/src"`

The pod5 library didn't compile correctly (can't just install it with pip).

**Comment by Elizabeth-mqz-gmz** [comment]
Oh, I see. I am not very familiar with compiling specific tools. 
Could you please guide me better in this issue? 

I already tried:
`make pod5-file-format`
But I get this:
```
Makefile:117: warning: ignoring prerequisites on suffix rule definition
make: Nothing to be done for 'pod5-file-format'.
```

**Comment by MBoemo** [comment]
Is using the singularity image an option? That will prevent you having to compile from source.

**Comment by Elizabeth-mqz-gmz** [comment]
I would like to leave that as last resource, so I can have all the installation of the software locally in the cluster. So I would like to try the compilation, and if that does not work, then use the singularity option.

**Comment by MBoemo** [comment]
Suggest following the general workflow in the singularity definition then and then trying to recompile DNAscent: https://github.com/MBoemo/DNAscent/blob/f1119c97494d267df6563f8bb178b41e40bad477/DNAscent.def#L16

**Comment by Elizabeth-mqz-gmz** [comment]
Got it, thank you so much, I'll try this!
