### ISSUE TITLE
Request a r10.4.1 DNA dataset with BrdU and EdU incorporation

### ISSUE THREAD

**Issue by hiruna72** [MBoemo/DNAscent#77]
Hello,

Thank you for building this great tool.

Can you share a r10.4.1 DNA dataset so that I can run and test DNAscent?

Thank you!

**Comment by MBoemo** [comment]
ENA accession PRJEB80561

**Comment by ywang285** [comment]
Hi @MBoemo, 

Thank you for sharing! I think this R10 data will be very useful for testing and troubleshooting. May I ask how long and at what concentration you treated the cells with BrdU/EdU for each of the samples below? Also, I assume that only the three samples labeled "V14_5kHz" were sequenced at 5 kHz using V14 chemistry—is that correct? Thank you!

1. ERR13726352	SAMEA116100924	ERX13127976	PRJEB80561	9606	Homo sapiens		ftp.sra.ebi.ac.uk/vol1/run/ERR137/ERR13726352/2024_05_21_MJ_ONT_RPE1_ATRi.tar.gz		
2. ERR13726349	SAMEA116100921	ERX13127973	PRJEB80561	9606	Homo sapiens		ftp.sra.ebi.ac.uk/vol1/run/ERR137/ERR13726349/2023_07_05_MJ_ONT_RPE1_unlabelled_trainingdata_V14_5khz.tar.gz		
3. ERR13726351	SAMEA116100923	ERX13127975	PRJEB80561	9606	Homo sapiens		ftp.sra.ebi.ac.uk/vol1/run/ERR137/ERR13726351/2023_07_05_MJ_ONT_RPE1_EdU_trainingdata_V14_5khz.tar.gz		
4. ERR13726350	SAMEA116100922	ERX13127974	PRJEB80561	9606	Homo sapiens		ftp.sra.ebi.ac.uk/vol1/run/ERR137/ERR13726350/2023_07_11_MJ_ONT_RPE1_BrdU_48hr_trainingdata_v14_5khz.tar.gz		
5. ERR13726353	SAMEA116100925	ERX13127977	PRJEB80561	9606	Homo sapiens		ftp.sra.ebi.ac.uk/vol1/run/ERR137/ERR13726353/2024_07_16_MJ_ONT_RPE1_untreated.tar.gz

**Comment by MBoemo** [comment]
These were 50 uM of each analogue - 72 hours for BrdU and 24 hours for EdU. All in RPE1 cells.
