### ISSUE TITLE
Using singularity input files not found

### ISSUE THREAD

**Issue by Pombeboy** [MBoemo/DNAscent#79]
Hi DNAscent team,

I installed DNAscent in my school's high performance computing cluster and used singularity command to run DNAscent. However, it reports errors showing input not found. All my input .pod5 are stored in the $POD5_DIR. The data has been basecalled by Dorado and the bam file is stored in $BAM_DIR. 

Here is my code: 

#!/bin/bash
#SBATCH --partition=gpu_quad                    # Partition to run in
#SBATCH --gres=gpu:1                         # GPU resources requested
#SBATCH -c 4                                 # Requested cores
#SBATCH --time=2-00:00                    # Runtime in D-HH:MM format
#SBATCH --mem=16GB                           # Requested Memory
#SBATCH -o %j.out                            # File to which STDOUT will be written, including job ID (%j)
#SBATCH -e %j.err                            # File to which STDERR will be written, including job ID (%j)

module load gcc/6.2.0 cuda/11.2

DS_DIR="/n/app/singularity/containers/jy214/DNAscent.sif"
POD5_DIR="/home/jy214/workingarea/2024-11-DiMeLo-seq/20241126_1347_MN47983_FBA70716_bbe50834/pod5"
BAM_DIR="/home/jy214/workingarea/2024-11-DiMeLo-seq/2024-12-04-DiMeLo-Dorado/output/bam"
BDRU_DIR="/home/jy214/moazed/jyu/2024-11-DiMeLo-seq/2024-12-08-DNAscent"
BDRU_BAM_DIR="/home/jy214/moazed/jyu/2024-11-DiMeLo-seq/2024-12-08-DNAscent/brdu_bam"
REF_GENOME="/home/jy214/workingarea/2024-11-DiMeLo-seq/2024-12-03-analysis/S_pombe_IGV.fa"
FORK_SENSE="/home/jy214/moazed/jyu/2024-11-DiMeLo-seq/2024-12-08-DNAscent/forksense"

singularity run --nv $DS_DIR index -f $POD5_DIR \
	-o $BDRU_DIR

singularity run --nv $DS_DIR detect -b $BAM_DIR/calls_2024-12-05_T02-14-53.bam \
	-r $REF_GENOME \
	-i $BDRU_DIR/index.dnascent \
	-o $BDRU_BAM_DIR/detect_output.bam

singularity run --nv $DS_DIR forkSense -d $BDRU_BAM_DIR/detect_output.bam \
	-o $FORK_SENSE/output.forkSense \
	-t 4 --markOrigins --markTerminations --markForks \
	--order BrdU,EdU

I received error in the report:

/app/DNAscent/bin/DNAscent: Relink `/app/DNAscent/tensorflow/lib/libtensorflow_framework.so.2' with `/lib/x86_64-linux-gnu/libz.so.1' for IFUNC symbol `crc32_z'
2024-12-10 11:23:39.076302: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
**Error opening directory: /home/jy214/workingarea/2024-11-DiMeLo-seq/20241126_1347_MN47983_FBA70716_bbe50834/pod5: No such file or directory**
terminate called after throwing an instance of 'IOerror'
  what():  Could not open file: /home/jy214/moazed/jyu/2024-11-DiMeLo-seq/2024-12-08-DNAscent
/var/spool/slurmd/job54518630/slurm_script: line 26: 67725 Aborted                 singularity run --nv $DS_DIR index -f $POD5_DIR -o $BDRU_DIR
/app/DNAscent/bin/DNAscent: Relink `/app/DNAscent/tensorflow/lib/libtensorflow_framework.so.2' with `/lib/x86_64-linux-gnu/libz.so.1' for IFUNC symbol `crc32_z'
2024-12-10 11:23:41.097592: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
terminate called after throwing an instance of 'IOerror'
  what():  Could not open file: /home/jy214/moazed/jyu/2024-11-DiMeLo-seq/2024-12-08-DNAscent/index.dnascent
/var/spool/slurmd/job54518630/slurm_script: line 31: 67771 Aborted                 singularity run --nv $DS_DIR detect -b $BAM_DIR/calls_2024-12-05_T02-14-53.bam -r $REF_GENOME -i $BDRU_DIR/index.dnascent -o $BDRU_BAM_DIR/detect_output.bam
/app/DNAscent/bin/DNAscent: Relink `/app/DNAscent/tensorflow/lib/libtensorflow_framework.so.2' with `/lib/x86_64-linux-gnu/libz.so.1' for IFUNC symbol `crc32_z'
2024-12-10 11:23:43.186898: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0

However, my pod5 is in the listed folder: /home/jy214/workingarea/2024-11-DiMeLo-seq/20241126_1347_MN47983_FBA70716_bbe50834/. I am wondering how can I solve this issue? Thank you.

- pombeboy

**Comment by MBoemo** [comment]
It's looking for a directory called `/home/jy214/workingarea/2024-11-DiMeLo-seq/20241126_1347_MN47983_FBA70716_bbe50834/pod` but you say the pod5 files are located in `/home/jy214/workingarea/2024-11-DiMeLo-seq/20241126_1347_MN47983_FBA70716_bbe50834`. My guess is that's the issue.

**Comment by MBoemo** [comment]
Can you paste the first few lines of the index file?
