### ISSUE TITLE
Is DNAscent compatible with BAM files containing other DNA modifications?

### ISSUE THREAD

**Issue by Pombeboy** [MBoemo/DNAscent#80]
Hi DNAscent team,

I successfully generated the index.dnascent file and pass it through the detect command. However, it generated an output_detect.bam that is empty based on samtools view. 

I am using DNAscent v4.0.3 with R10.4.1 pore. I used Dorado|SUP model to call all modifications as my samples also contain 6mA modifications, which I assume the BAM file would contain MM and ML tags on 6mA. Is DNAscent compatible with a BAM file containing MM/ML on other modifications? I am currently doing an unmodified basecalling to see whether there is any difference.

Here is the error report:
/app/DNAscent/bin/DNAscent: Relink `/app/DNAscent/tensorflow/lib/libtensorflow_framework.so.2' with `/lib/x86_64-linux-gnu/libz.so.1' for IFUNC symbol `crc32_z'
2024-12-11 08:41:27.283784: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
/app/DNAscent/bin/DNAscent: Relink `/app/DNAscent/tensorflow/lib/libtensorflow_framework.so.2' with `/lib/x86_64-linux-gnu/libz.so.1' for IFUNC symbol `crc32_z'
2024-12-11 08:41:55.888843: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2024-12-11 08:42:08.688509: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2024-12-11 08:42:09.111093: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2400000000 Hz
/app/DNAscent/bin/DNAscent: Relink `/app/DNAscent/tensorflow/lib/libtensorflow_framework.so.2' with `/lib/x86_64-linux-gnu/libz.so.1' for IFUNC symbol `crc32_z'
2024-12-11 08:44:20.456969: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
terminate called after throwing an instance of 'ForkSenseData'
  what():  Not enough data was passed to forkSense to reliably segment analogue regions. Data passed in bam or detect format and should include at least several hundred reads.
/var/spool/slurmd/job54622361/slurm_script: line 33: 13124 Aborted                 singularity run -B $BINDER:$BINDER --nv $DS_DIR forkSense -d $BDRU_DIR/detect_output.bam -o $BDRU_DIR/output.forkSense -t 4 --markOrigins --markTerminations --markForks --order BrdU,EdU

Output report:
[=>                                 ]   4%    1/24   0hr 0min40sec  
[==>                                ]   8%    2/24   0hr 0min35sec  
[====>                              ]  12%    3/24   0hr 0min29sec  
[=====>                             ]  16%    4/24   0hr 0min25sec  
[=======>                           ]  20%    5/24   0hr 0min22sec  
[========>                          ]  25%    6/24   0hr 0min20sec  
[==========>                        ]  29%    7/24   0hr 0min19sec  
[===========>                       ]  33%    8/24   0hr 0min18sec  
[=============>                     ]  37%    9/24   0hr 0min17sec  
[==============>                    ]  41%   10/24   0hr 0min16sec  
[================>                  ]  45%   11/24   0hr 0min15sec  
[=================>                 ]  50%   12/24   0hr 0min14sec  
[==================>                ]  54%   13/24   0hr 0min13sec  
[====================>              ]  58%   14/24   0hr 0min12sec  
[=====================>             ]  62%   15/24   0hr 0min10sec  
[=======================>           ]  66%   16/24   0hr 0min 8sec  
[========================>          ]  70%   17/24   0hr 0min 7sec  
[==========================>        ]  75%   18/24   0hr 0min 6sec  
[===========================>       ]  79%   19/24   0hr 0min 5sec  
[=============================>     ]  83%   20/24   0hr 0min 4sec  
[==============================>    ]  87%   21/24   0hr 0min 3sec  
[================================>  ]  91%   22/24   0hr 0min 2sec  
[=================================> ]  95%   23/24   0hr 0min 1sec  
[===================================] 100%   24/24   0hr 0min 0sec  
Loading DNAscent index... ok.
Importing reference... ok.
Opening bam file... ok.
Scanning bam file...ok.

the output_detect.bam is essentially empty. 

Thanks.

-P

**Comment by MBoemo** [comment]
Should be - there was an issue with this a few months ago but it's been fixed so make sure you've pulled the latest image. Also suspicious that you only have 24 reads passing QCs - check that they didn't all fail.
