### ISSUE TITLE
basecalling model question

### ISSUE THREAD

**Issue by simonecaniONT** [MBoemo/DNAscent#81]
Dear Michael and team,

maybe a really simple question related more to the experimental set-up rather than data analysis.
I see that the recommended basecalling model is the dna_r10.4.1_e8.2_400bps_fast@v5.0.0
Is there any specific reason for it? is it possible (or better) to use one of the HAC or SUP basecalling models available in Dorado or Minknow (in case I want to use live basecalling during sequencing)?

Thank you in advance.
Regards

**Comment by MBoemo** [comment]
A good question - it's really just time saving. The basecall doesn't have to be that accurate for the software to work well and the analogue will affect the basecalling anyway, so we typically just use the fast one.

**Comment by simonecaniONT** [comment]
Thanks for your feedback, really appreciated!
